### ISSUE TITLE
关于serverless.yml的触发器问题

### ISSUE THREAD

**Issue by Vincentzhengwei** [LXK9301/jd_scripts#1]
这个配置文件插入定时触发器，argument: jd_superMarket&jd_family，用这个&符号创建出来在腾讯云上面，没有办法运行。需要重新创建定时器，argument拆分成2行，才能运行2个js，但我知道这个配置文件应该怎么写，哪位大佬后续可以优化下

**Comment by LXK9301** [comment]
不可能啊

@DoveBoy

**Comment by DoveBoy** [comment]
@Vincentzhengwei 请提供日志，目前使用过程中未出现过这个问题，请检查自身的配置问题

**Comment by Vincentzhengwei** [comment]
@DoveBoy 通过serverless deploy上传成功如图一，然后生成的触发器如图二，显示报错如图三（找不到文件）
![image](https://user-images.githubusercontent.com/32627913/104873226-fc688800-598a-11eb-8d5a-511fd9fb4c88.png)
![image](https://user-images.githubusercontent.com/32627913/104873488-97616200-598b-11eb-9677-e838a1a223ab.png)
![image](https://user-images.githubusercontent.com/32627913/104873436-7b5dc080-598b-11eb-9bad-4a8d2553380a.png)

当我在触发器修改成如下图形式后，才能够同时触发几个js（也就是不能用&连接需要分行）
![image](https://user-images.githubusercontent.com/32627913/104873561-c5df3d00-598b-11eb-9373-e08c71561357.png)

感谢大佬回复！

**Comment by Vincentzhengwei** [comment]
@DoveBoy 通过实验，可以采取以下方式写入，可以获得正常的换行，同时触发多个js

argument: "jd_blueCoin\n\
jd_club_lottery\n\
jd_car\n\
jd_car_exchange"
![image](https://user-images.githubusercontent.com/32627913/104875027-46ec0380-598f-11eb-9ee4-65134cb75140.png)
![image](https://user-images.githubusercontent.com/32627913/104875038-4c494e00-598f-11eb-97b8-c765ac48dcc9.png)

**Comment by DoveBoy** [comment]
@Vincentzhengwei 云函数同时触发多个js并行运行，测试功能选择`Time定时触发器事件模板`，修改message里面的内容，格式为`1.js&2.js&3.js`以此类推

**Comment by Vincentzhengwei** [comment]
@DoveBoy Time定时触发器事件模板测试，这个是没问题的。我的意思是如果要用serverless deploy上传云函数，直接自动生成定时触发器的情况下不行。使用serverless deploy同步后，我需要去删除原来的定时触发器，然后再重新创建10个定时器，这样就不够自动化

**Comment by DoveBoy** [comment]
@Vincentzhengwei 首先按照下图一的方式测试一下，如果正常的话，按照图二的方式手动新建一个定时器方式测试一下，如果依旧正常，说明这样的触发方式没有问题（前提是你没改过repo里面的任何内容）。如果你的问题依旧，那我也不知道了，没遇到过这样的问题，建议重新deploy吧
![image](https://user-images.githubusercontent.com/19201447/104910184-e7f4b180-59c3-11eb-9224-018e298fe6e4.png)
![image](https://user-images.githubusercontent.com/19201447/104910668-9dc00000-59c4-11eb-8e92-fc0f1d126c0c.png)
