### ISSUE TITLE
宠汪汪兑换京豆bug

### ISSUE THREAD

**Issue by Yvan0329** [LXK9301/jd_scripts#101]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] Docker1 
- [x] Docker2 
- [ ] 系统直装 
- [ ] iOS代理软件

### (1) 具体问题
A：
宠汪汪兑换京豆显示api错误，网络正常
### (2) 详细日志
A：
本地时间与京东服务器时间差(毫秒)：-859
当前积分 51260

宠物等级 24

京东昵称 大白

当前京豆库存:270
saleInfoId:193
当前账户积分:51260
当前京豆库存:270
满足兑换条件,开始为您兑换京豆

{"name":"HTTPError","timings":{"start":1611072036189,"socket":1611072036190,"lookup":1611072036190,"connect":1611072036225,"secureConnect":1611072036314,"upload":1611072036314,"response":1611072045083,"end":1611072045083,"phases":{"wait":1,"dns":0,"tcp":35,"tls":89,"request":0,"firstByte":8769,"download":0,"total":8894}}}
宠汪汪积分兑换奖品 API请求失败，请检查网路重试
兑换京豆异常:undefined

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by LXK9301** [comment]
已修复

https://github.com/LXK9301/jd_scripts/compare/a9b71fbacfdc...1927a8431865
