### ISSUE TITLE
账号管理的相关问题

### ISSUE THREAD

**Issue by github-9233** [LXK9301/jd_scripts#103]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] Docker1 
- [ ] Docker2 
- [ ] 系统直装 
- [x] iOS代理软件

### (1) 具体问题
A：Loon每次跑脚本的时候都会跑两次同样的账号，账号1和账号2相同

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by LXK9301** [comment]
注：如与NobyDa的京东cookie出现重复，建议在此处删除重复的cookie

**Comment by LXK9301** [comment]
更新订阅后 ，看boxjs 京东多ck管理的提示。
