### ISSUE TITLE
Can't find variable: process

### ISSUE THREAD

**Issue by canyesh** [LXK9301/jd_scripts#105]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] Docker1 
- [ ] Docker2 
- [ ] 系统直装 
- [x] iOS代理软件

### (1) 具体问题
A：

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EchoChan314** [comment]
更新最新版，已解决。
