### ISSUE TITLE
这无疑是一个伟大的脚本，但是却对新手和小白极其不友好。

### ISSUE THREAD

**Issue by FREEZXC** [LXK9301/jd_scripts#107]
## 期望增加的功能

A：这无疑是一个伟大的脚本，但是却对新手和小白极其不友好，我希望此项目的开发人员和维护者，可以出一个面向新手的教程，原项目省略的步骤实在很多，特别是docker一的教程里的hosts使我的解析太慢，以至于完全git pull不到。

当然只是一个建议。

## 入口

A：

**Comment by ryonalish** [comment]
因为...不是新手向，教程已经很详细了，还觉得不够详细说明不适合参与。

**Comment by EchoChan314** [comment]
你不要给作者带高帽。
这玩意，就该低调使用。

**Comment by tangchaoliziyo** [comment]
解析慢这不是你自己的问题吗？国内连github本来就慢，还有教程已经很简单了只要读过高中认真上过几节语文课都能看懂这是什么意思
