### ISSUE TITLE
关于centos 的挂机问题

### ISSUE THREAD

**Issue by lh44575858** [LXK9301/jd_scripts#114]
使用 centos搭建的跑脚本，使用pm2 运行挂机，4个账号，但是挂机只挂机一个账号的 活动，希望大佬修复

**Comment by LXK9301** [comment]
自己cookie填写不对 或者不规范

**Comment by lh44575858** [comment]
https://pic.sevesum.com/2021/01/20/c6447e0b3269f.png
格式没什么问题么，老大，不知道为啥 就行不行

**Comment by EvineDeng** [comment]
> https://pic.sevesum.com/2021/01/20/c6447e0b3269f.png
> 格式没什么问题么，老大，不知道为啥 就行不行

重新启动挂机程序试试。

**Comment by lh44575858** [comment]
https://pic.sevesum.com/2021/01/20/ec0036b22c25f.png

刚刚重启了下，还是不行 不知道啥情况

**Comment by lh44575858** [comment]
老大 看看呗
