### ISSUE TITLE
OpenWRT部署，config文件不同步和挂机程序不执行

### ISSUE THREAD

**Issue by xiaojun-chang1224** [LXK9301/jd_scripts#119]
感谢大佬精心制作这样一个平台，我在软路由上安装之后，有两个问题还请大佬查看一下：
1，大佬仓库里的config文件已经更新到3.15.1了，但是我这里还是3.14.0，已经pull过了；
2，疯狂的Joy挂机程序不会自动执行，手动执行之后出现下列代码
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [jd_crazy_joy_coin.js](ids: [ 1 ])
[PM2] [jd_crazy_joy_coin](1) ✓
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 1  │ jd_crazy_joy_coin  │ fork     │ 305… │ online    │ 0%       │ 16.1mb   │
│ 0  │ server             │ fork     │ 394… │ online    │ 106.9%   │ 26.3mb   │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘

谢谢大佬！

**Comment by EvineDeng** [comment]
@xiaojun-chang1224 你自己的配置文件，需要你自己更新。

**Comment by xiaojun-chang1224** [comment]
@EvineDeng 大佬，是更新哪一部分呢？“定时设定”中都已经改了，“挂机”没有找到在哪里改，“config.sh"不是应该自动更新的吗？还望赐教

**Comment by EvineDeng** [comment]
@xiaojun-chang1224 请仔仔细细、仔仔细细、仔仔细细地阅读wiki。
