### ISSUE TITLE
jd_scripts.syno.json里面的"image" : "lxk0301/jd_scripts"地址问题

### ISSUE THREAD

**Issue by PoatWee** [LXK9301/jd_scripts#127]
大佬，群晖的三个jd_scripts.syno.json里面的"image" : "lxk0301/jd_scripts"地址，是不是都写错了，提示没有这个镜像，应该是"image" : "akyakya/jd_scripts",吧。

**Comment by LXK9301** [comment]
没写错

https://hub.docker.com/r/lxk0301/jd_scripts/tags?page=1&ordering=last_updated

**Comment by iouAkira** [comment]
插一句，群晖要先把用作者那个链接 https://hub.docker.com/r/lxk0301/jd_scripts/ 手动拉下来 ，或者ssh进群晖用 `docker pull lxk0301/jd_scripts:latest`  拉下来  之后在导入json

**Comment by PoatWee** [comment]
我已经发现这个问题了，之前没有注意，正在搞

**Comment by PoatWee** [comment]
谢谢
