### ISSUE TITLE
大佬能照顾下qnap用户怎么添加服务吗

### ISSUE THREAD

**Issue by hs20073** [LXK9301/jd_scripts#13]

**Comment by EvineDeng** [comment]
方法一方法二都可以，怎么叫没照顾？

**Comment by hs20073** [comment]
就是docker hub上的镜像怎么应用🙈

**Comment by EvineDeng** [comment]
教程都写得很清楚了，会不会是你自己的事。

**Comment by nick814** [comment]
你可以先去百度下 qnap怎么用docker 其他都一样 你只要会用qnap的docker界面就行了

**Comment by hs20073** [comment]
> 你可以先去百度下 qnap怎么用docker 其他都一样 你只要会用qnap的docker界面就行了

大概了解了，ssh进去不是那么熟悉暂时不敢瞎弄；qnap的Container Station提供的docker hub搜索搜不出LXK大佬的资源，然后就是创建容器一些细节事项不知道怎么填上🤣

**Comment by iouAkira** [comment]
@hs20073 建议ssh进去使用docker-compose方式启动，不瞎搞没啥问题，威联通应该也是安装docker之后自带docker-compose的，注意ssh进去需要sudo -i 切换到root用户才能使用docker

**Comment by superculu** [comment]
Container Station -> 创建 -> 右上角点"创建应用程序", 然后将docker-compose内容粘贴进去就能创建成功, 很简单的, 不要通过搜索创建

**Comment by hs20073** [comment]
> Container Station -> 创建 -> 右上角点"创建应用程序", 然后将docker-compose内容粘贴进去就能创建成功, 很简单的, 不要通过搜索创建

往后cookie等这些参数更改怎么弄？
