### ISSUE TITLE
神仙书院运行失败

### ISSUE THREAD

**Issue by qiebu3509** [LXK9301/jd_scripts#135]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [X] 没有类似的issue 

Q：是否仔细阅读了教程
- [X] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] Docker1 
- [x] Docker2 
- [ ] 系统直装 
- [ ] iOS代理软件

### (1) 具体问题
A：京东神仙书院运行失败

### (2) 详细日志
A：原因: SyntaxError: Unexpected token . in JSON at position 12!

### (1) Node.js版本

A：v8.10.0

### (2) npm版本

A：3.5.2

### (3)npm install的日志

A：

**Comment by xufeiwu123** [comment]
我都没找到这个书院脚本在哪里

**Comment by qiebu3509** [comment]
> 我都没找到这个书院脚本在哪里

已经修复好了，现在没问题了

**Comment by xufeiwu123** [comment]
> > 我都没找到这个书院脚本在哪里
> 
> 已经修复好了，现在没问题了

不是，我意思是我没在仓库里面找到神仙书院的脚本，然后再issue看到有人提神仙书院，所以我就想问问能不能指出神仙书院脚本是哪个

**Comment by qiebu3509** [comment]
> > > 我都没找到这个书院脚本在哪里
> > 
> > 
> > 已经修复好了，现在没问题了
> 
> 不是，我的意思是我没在仓库里面找到神仙书院的脚本，然后再发行看到有人提神仙书院，所以我就想问问能不能指出神仙书院脚本是其中一个

jd_immortal.js   这个
