### ISSUE TITLE
云函数部署报错

### ISSUE THREAD

**Issue by charleyyy** [LXK9301/jd_scripts#137]
Actions部署到云函数时报错
Request failed with status code 400 
尝试多次无法解决
望解决，感谢！

**Comment by Vincentzhengwei** [comment]
Actions部署到云函数时报错
Request failed with status code 400

又再次报错了

**Comment by zing518** [comment]
嗯  报错了

**Comment by q4w5e6** [comment]
和昨天的毛病一样，触发器的字符过长

**Comment by charleyyy** [comment]
> 和昨天的毛病一样，触发器的字符过长

今天刚想明白这个问题，谢谢 以前我自己也触发过一次...感谢

**Comment by zing518** [comment]
现在你们可以部署到腾讯云函数吗？
