### ISSUE TITLE
关于互助码的填写

### ISSUE THREAD

**Issue by heyzhu** [LXK9301/jd_scripts#14]
京东账号1的shareCode1@京东账号1的shareCode2&京东账号2的shareCode1@京东账号2的shareCode2
1、@符号用于分割同一账号的不同活动的shareCode，是这么个意思吗？
2、单容器情况下，shareCode填写是否要对应账号顺序？
求大佬解惑

**Comment by Misaka09982** [comment]
多看点wiki，用@隔开的是要助力不同的人，用＆隔开是你的第二个账号要助力的，实在搞不懂的，自己填写进去跑一遍不就知道了

**Comment by koo9966** [comment]
哪位大佬，能出个腾讯云部署，详细教程，照顾一下小白
