### ISSUE TITLE
京喜农场重复提示“助力码与当前账号相同，跳过助力。准备进行下一个助力”

### ISSUE THREAD

**Issue by gnowmil** [LXK9301/jd_scripts#142]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否仔细阅读了教程
- [ x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ x] Docker1 
- [ ] Docker2 
- [ ] 系统直装 
- [ ] iOS代理软件

### (1) 具体问题
A：重复提示“助力码与当前账号相同，跳过助力。准备进行下一个助力”，运行了10多分钟也没有停，直到手动终止。尝试重新执行也是出现同样的错误提票。

### (2) 详细日志
A：
************* 检查【京东账号2】jd_483eed7052d1d cookie 是否有效 *************
开始【京东账号2】jd_483eed7052d1d

由于您第2个京东账号未提供shareCode,将采纳本脚本自带的助力码
第2个京东账号将要助力的好友["22bd6fbbabbaa770a45ab2607e7a1e8a","197c6094e965fdf3d33621b47719e0b1"]
获取用户信息 & 任务列表
获取任务列表  总共0个任务！
【京东账号2（jd_483eed7052d1d）的京喜农场好友互助码】 33a05e1abbf00478a6cb531938fd63df
【京东账号2（jd_483eed7052d1d）的京喜农场种子active】 jdnc_1_caomi210113_2
获取任务列表  总共0个任务！
邀请码提交失败 API 返回异常
即将助力 share code：22bd6fbbabbaa770a45ab2607e7a1e8a
助力结果：ret=1011 retmsg="shareuser not join this active"
即将助力 share code：197c6094e965fdf3d33621b47719e0b1
助力结果：ret=1011 retmsg="shareuser not join this active"
获取随机助力码成功 200 33a05e1abbf00478a6cb531938fd63df
助力码与当前账号相同，跳过助力。准备进行下一个助力
即将助力 share code：33a05e1abbf00478a6cb531938fd63df
助力结果：ret=1021 retmsg="cannot helf self"
获取随机助力码成功 200 33a05e1abbf00478a6cb531938fd63df
助力码与当前账号相同，跳过助力。准备进行下一个助力
即将助力 share code：33a05e1abbf00478a6cb531938fd63df
助力结果：ret=1021 retmsg="cannot helf self"
获取随机助力码成功 200 33a05e1abbf00478a6cb531938fd63df
助力码与当前账号相同，跳过助力。准备进行下一个助力
即将助力 share code：33a05e1abbf00478a6cb531938fd63df
助力结果：ret=1021 retmsg="cannot helf self"
获取随机助力码成功 200 33a05e1abbf00478a6cb531938fd63df
助力码与当前账号相同，跳过助力。准备进行下一个助力
即将助力 share code：33a05e1abbf00478a6cb531938fd63df
助力结果：ret=1021 retmsg="cannot helf self"
获取随机助力码成功 200 33a05e1abbf00478a6cb531938fd63df
助力码与当前账号相同，跳过助力。准备进行下一个助力
即将助力 share code：33a05e1abbf00478a6cb531938fd63df
助力结果：ret=1021 retmsg="cannot helf self"
获取随机助力码成功 200 33a05e1abbf00478a6cb531938fd63df
助力码与当前账号相同，跳过助力。准备进行下一个助力
即将助力 share code：33a05e1abbf00478a6cb531938fd63df
助力结果：ret=1021 retmsg="cannot helf self"
获取随机助力码成功 200 33a05e1abbf00478a6cb531938fd63df
助力码与当前账号相同，跳过助力。准备进行下一个助力
即将助力 share code：33a05e1abbf00478a6cb531938fd63df
助力结果：ret=1021 retmsg="cannot helf self"
获取随机助力码成功 200 33a05e1abbf00478a6cb531938fd63df
助力码与当前账号相同，跳过助力。准备进行下一个助力
即将助力 share code：33a05e1abbf00478a6cb531938fd63df

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by LXK9301** [comment]
@FanchangWang

**Comment by FanchangWang** [comment]
这是 api 重复返回同一个助力码导致的。明天我改下跳出逻辑，把这种重复次数也算到容错次数中。等我提 pr 吧

**Comment by FanchangWang** [comment]
已提交修复 pr #155

**Comment by gnowmil** [comment]
大神动作神速，世界有你们更精彩。
