### ISSUE TITLE
疯狂的joy执行失败

### ISSUE THREAD

**Issue by dclemon** [LXK9301/jd_scripts#150]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [x] Docker1 
- [ ] Docker2 
- [ ] 系统直装 
- [ ] iOS代理软件

### (1) 具体问题
A：提示command not found(之前可以执行)
环境是群晖docker

### (2) 详细日志
A：
root@evinedeng-jd1:/jd/scripts $ bash jd_crazy_joy_coin.js                                                             
jd_crazy_joy_coin.js: line 1: /bin: Is a directory                                                                     
jd_crazy_joy_coin.js: line 2: crazy: command not found                                                                 
jd_crazy_joy_coin.js: line 3: 挂机领金币/宝箱专用: No such file or directory                                           
jd_crazy_joy_coin.js: line 6: 已支持IOS双京东账号,Node.js支持N个京东账号: command not found                            
jd_crazy_joy_coin.js: line 7: 脚本兼容:: command not found                                                             
jd_crazy_joy_coin.js: line 8: ============Quantumultx===============: command not found                                
jd_crazy_joy_coin.js: line 9: [task_local]: command not found                                                          
jd_crazy_joy_coin.js: line 11: 10: command not found                                                                   
jd_crazy_joy_coin.js: line 13: ================Loon==============: command not found                                   
jd_crazy_joy_coin.js: line 14: [Script]: command not found                                                             
jd_crazy_joy_coin.js: line 15: cron: command not found                                                                 
jd_crazy_joy_coin.js: line 17: ===============Surge=================: command not found                                
jd_crazy_joy_coin.js: line 18: crazyJoy挂机: command not found                                                         
jd_crazy_joy_coin.js: line 20: ============小火箭=========: command not found                                          
jd_crazy_joy_coin.js: line 21: crazyJoy挂机: command not found                                                         
jd_crazy_joy_coin.js: line 23: Loon/: Is a directory                                                                   
jd_crazy_joy_coin.js: line 26: syntax error near unexpected token `('                                                  
jd_crazy_joy_coin.js: line 26: `const $ = new Env('crazyJoy挂机');'  

### (1) Node.js版本

A：v14.15.4  

### (2) npm版本

A：6.14.10    

### (3)npm install的日志

A：

**Comment by LXK9301** [comment]
docker 群晖你自己检查吧。 脚本是正常的。

**Comment by sgzman** [comment]
> docker 群晖你自己检查吧。 脚本是正常的。

希望可以设置一下joy挂机每天夜里停一个小时，或者间歇性的停一下，防止黑号
