### ISSUE TITLE
docke1r log 疯狂刷屏报错

### ISSUE THREAD

**Issue by AboutCXJ** [LXK9301/jd_scripts#152]
## 1.关于你要提交的问题
docker log 疯狂刷屏报错

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否仔细阅读了教程
- [x ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法
- [ x] Docker1 
- [ ] Docker2 
- [ ] 系统直装 
- [ ] iOS代理软件

### (1) 具体问题
A：

### (2) 详细日志
A：

<img width="1160" alt="截屏2021-01-21 上午11 13 25" src="https://user-images.githubusercontent.com/19811825/105275272-e6043b80-5bd9-11eb-875d-166d92779058.png">

**Comment by LXK9301** [comment]
看着像是随机ua文件的问题 你更新脚本再试试看
