### ISSUE TITLE
神仙书店的经纬度，可以设置成多账号&的形式嘛

### ISSUE THREAD

**Issue by zhuyaozi** [LXK9301/jd_scripts#156]
## 期望增加的功能

A：神仙书店的经纬度，设置成多账号&的形式

## 入口

A：这个变量如果如果只用一个，怕是会一锅端哦😅

**Comment by liwenjie119** [comment]
好像自动获取经纬度不管用啊，自动获取的经纬度全在北京
提供的地理位置信息为{"lng":"116.397128","lat":"39.916527"}

**Comment by xufeiwu123** [comment]
我怎么找不到神仙书店的脚本啊，怎么你们都用了

**Comment by liwenjie119** [comment]
> 我怎么找不到神仙书店的脚本啊，怎么你们都用了

jd_immortal

**Comment by LXK9301** [comment]
> ## 期望增加的功能
> A：神仙书店的经纬度，设置成多账号&的形式
> 
> ## 入口
> A：这个变量如果如果只用一个，怕是会一锅端哦😅

不能。临时活动脚本。别搞那么多要求
