### ISSUE TITLE
【题外话】求大神写一个学习强国的脚本

### ISSUE THREAD

**Issue by hupo376787** [LXK9301/jd_scripts#161]
## 期望增加的功能

A：求大神写一个学习强国的脚本，类似这个jd脚本一样

## 入口

A：null

**Comment by ccboxjole** [comment]
搜索一下，很多吧....

**Comment by hupo376787** [comment]
有autojs，需要安卓机运行。

没有类似docker的

**Comment by ccboxjole** [comment]
> 有autojs，需要安卓机运行。
> 
> 没有类似docker的

https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo

**Comment by hupo376787** [comment]
@ccboxjole 谢谢，之前我也看过这个，没注意到
