### ISSUE TITLE
更新活动内容

### ISSUE THREAD

**Issue by happinesslijian** [LXK9301/jd_scripts#163]
更新crontab_list.sh
根据项目https://github.com/shylocks/Loon/blob/main/docker/crontab_list.sh  得知现在已经有了红包雨等活动
具体js详见https://github.com/shylocks/Loon
可以整合到本项目中
望尽快采纳！

**Comment by 345784078** [comment]
docker2有了 。

**Comment by happinesslijian** [comment]
> docker2有了 。

docker2是哪个？
我现在是自己搞的一个临时的。反正也能用
