### ISSUE TITLE
关于京喜农场助力码问题

### ISSUE THREAD

**Issue by hclasmn** [LXK9301/jd_scripts#17]
惊喜农场助力提示1011，返回助力失败信息：shareuser not join this active"，请问怎么解决，是助力码要填写上active么？
- JXNC_SHARECODES=2d443ee000b95e3ccbbebc5c701ea54d

**Comment by ChicBrother** [comment]
我也碰到了，好像给指定的助力都会出现这个提示，不知成功了没有。

**Comment by hclasmn** [comment]
> 我也碰到了，好像给指定的助力都会出现这个提示，不知成功了没有。

没成功 没助力在规定时间完成不了的

**Comment by zhu1979** [comment]
@ChicBrother 我的也是报这个msg

**Comment by creazy412** [comment]
话说 app 的 token 是怎么获取到的？谢谢

**Comment by lqrqw** [comment]
> 惊喜农场助力提示1011，返回助力失败信息：shareuser not join this active"，请问怎么解决，是助力码要填写上active么？
> 
> * JXNC_SHARECODES=2d443ee000b95e3ccbbebc5c701ea54d

看了下脚本，是原作者whyour加的一个active code

**Comment by hclasmn** [comment]
> > 惊喜农场助力提示1011，返回助力失败信息：shareuser not join this active"，请问怎么解决，是助力码要填写上active么？
> > 
> > * JXNC_SHARECODES=2d443ee000b95e3ccbbebc5c701ea54d
> 
> 看了下脚本，是原作者whyour加的一个active code

要写进去？格式呢？求教

**Comment by zhifeng456** [comment]
> 话说 app 的 token 是怎么获取到的？谢谢

同问，试了httpcanary抓包没找到，不会玩。

**Comment by Dacanid** [comment]
> > 话说 app 的 token 是怎么获取到的？谢谢
> 
> 同问，试了httpcanary抓包没找到，不会玩。

https://raw.githubusercontent.com/LXK9301/jd_scripts/master/jd_jxnc.js

脚本中描述
[task_local]
0 9,12,18 * * * https://raw.githubusercontent.com/LXK9301/jd_scripts/master/jd_jxnc.js, tag=京喜农场, img-url=https://raw.githubusercontent.com/58xinian/icon/master/jxnc.png, enabled=true
[rewrite_local]
^https\:\/\/wq\.jd\.com\/cubeactive\/farm\/dotask url script-request-header https://raw.githubusercontent.com/whyour/hundun/master/quanx/jx_nc.cookie.js

hostname = wq.jd.com

有三个内容要填。
我设置好后也同样遇到了京喜农场种子token的问题

--------------------------
我在京喜农场中做了两个任务，在日志里也可以搜到farm_jstoken":"xxx","timestamp":"xxx","phoneid":"xxx-xxx格式的token，但是还没找到在哪填上去。现在是运行jd_jxnc.js 提示还是要种子 token

**Comment by RitaZengMumu** [comment]
我的token也填了，但是运行直接报错，不知道是什么原因

开始第1个任务：去玩炸年兽分10亿
去玩炸年兽分10亿[做任务]：ret:1032 retmsg:"err operate env"
任务执行失败，种植的 APP 专属种子，请提供 token 或种植非 APP 种子

==============📣系统通知📣==============
京喜农场
【京东账号1】jd_々呵呵
【水果名称】铁棍山药
任务执行失败，种植的 APP 专属种子，请提供 token 或种植非 APP 种子

**Comment by a136080204** [comment]
开始第1个任务：去达达惊喜提现
去达达惊喜提现[做任务]：ret:1032 retmsg:"err operate env"
任务执行失败，种植的 APP 专属种子，请提供 token 或种植非 APP 种子

==============📣系统通知📣==============
京喜农场
【京东账号1】55
【水果名称】冰糖橙
任务执行失败，种植的 APP 专属种子，请提供 token 或种植非 APP 种子
