### ISSUE TITLE
京东赚赚出现2个新任务，脚本提示：活动太火爆，但进入后手动点击可完成。

### ISSUE THREAD

**Issue by servicehost** [LXK9301/jd_scripts#171]
在任务列表中出现的2个新任务，执行脚本时总会提示：

去做任务：关注德青源赢好礼
任务失败，错误信息：啊哦，活动太火爆～~
去做任务：逛逛爆款礼盒
任务失败，错误信息：啊哦，活动太火爆～~

但手动进入操作后则可正常完成，证明与账号无关。

**Comment by sxx1314** [comment]
惊喜工厂也遇到这问题。任务都是火爆，但是手动都可以做完。

**Comment by 9k001** [comment]
怎么获取到账号的互助码？

**Comment by shylocks** [comment]
fixed in 645d978825acaeaecacfed0aa4ebe7a95bd60a21
