### ISSUE TITLE
京喜工厂参团失败

### ISSUE THREAD

**Issue by qiangxinglin** [LXK9301/jd_scripts#172]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [x] Docker1 
- [ ] Docker2 
- [ ] 系统直装 
- [ ] iOS代理软件

### (1) 具体问题
A：
参团相关逻辑问题, 无论是第一个团主账号, 还是之后的副账号, 均显示以下信息
### (2) 详细日志
A：
`参团失败：{"msg":"活动已结束，请稍后再试~","nowTime":1611224905,"ret":10218}`

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by LXK9301** [comment]
是今天开团的活动id变了。然后我忘记更新了
