### ISSUE TITLE
炸年兽脚本无法自动下一关

### ISSUE THREAD

**Issue by MisterGlasses** [LXK9301/jd_scripts#175]
脚本获取到的开启下一关所需的爆竹数量比实际需要的大的多，望大佬核查。

**Comment by LXK9301** [comment]
我这边看到的是， 脚本显示需要的比实际的还少。 反正又不影响开启下一关

**Comment by MisterGlasses** [comment]
> 我这边看到的是， 脚本显示需要的比实际的还少。 反正又不影响开启下一关

我两个号都是显示需要133万 实际需要18万 然后就不会升级了 如果只有我这样就无所谓 反正我每天都会手动玩的

**Comment by shylocks** [comment]
fix in b4547bdd2e58bc8b26e73429176460b2d577bdb7

**Comment by MisterGlasses** [comment]
多谢大佬
