### ISSUE TITLE
嘿嘿，老大的脚本圈X图标全部重置完毕，需要的自取~

### ISSUE THREAD

**Issue by yogayyy** [LXK9301/jd_scripts#199]
分了两个版本：Light&Dark，按需自取：
[Light版本](https://raw.githubusercontent.com/yogayyy/Scripts/master/QuantumultX/lxk0301_light.json "Light版本")  
[Dark版本](https://raw.githubusercontent.com/yogayyy/Scripts/master/QuantumultX/lxk0301_dark.json "Dark版本")

老大如有需要的仓库自取即可。

![效果图](https://raw.githubusercontent.com/yogayyy/Scripts/master/Icon/example/readme_example.jpg)

**Comment by LXK9301** [comment]
好。感谢。

**Comment by fengmikaelson** [comment]
小火箭应该用哪个脚本，只看到其他三个

**Comment by yogayyy** [comment]
> 小火箭应该用哪个脚本，只看到其他三个

@fengmikaelson 圈x用的，跟小火箭没关系~

**Comment by Aoyy-zy** [comment]
打不开啊
