### ISSUE TITLE
关于tg推送错误

### ISSUE THREAD

**Issue by ASSAULT-FOX** [LXK9301/jd_scripts#20]
配置的tg推送无论在本地还是云函数都无法正常推送，其他的就正常

**云函数执行后输出的日志：**
```
2021-01-17T06:44:46.914Z 711a3fd8-9b40-4cd3-9dc8-2d9601fe2ae9 telegram发送通知消息失败！！

2021-01-17T06:44:46.914Z 711a3fd8-9b40-4cd3-9dc8-2d9601fe2ae9 RequestError: connect ETIMEDOUT 31.13.68.1:443

    at ClientRequest.<anonymous> (/var/user/node_modules/got/dist/source/core/index.js:953:111)

    at Object.onceWrapper (events.js:418:26)

    at ClientRequest.emit (events.js:323:22)

    at ClientRequest.origin.emit (/var/user/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)

    at TLSSocket.socketErrorListener (_http_client.js:426:9)

    at TLSSocket.emit (events.js:311:20)

    at emitErrorNT (internal/streams/destroy.js:92:8)

    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)

    at processTicksAndRejections (internal/process/task_queues.js:84:21)

    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {

  name: 'RequestError',

  code: 'ETIMEDOUT',

  timings: {

    start: 1610865759672,

    socket: 1610865759672,

    lookup: 1610865759677,

    connect: undefined,

    secureConnect: undefined,

    upload: undefined,

    response: undefined,

    end: undefined,

    error: 1610865886914,

    abort: undefined,

    phases: {

      wait: 0,

      dns: 5,

      tcp: undefined,

      tls: undefined,

      request: undefined,

      firstByte: undefined,

      download: undefined,

      total: 127242

    }

  }

}
```

**Comment by LXK9301** [comment]
@ASSAULT-FOX 。。。。。需要你的设备可以访问外网，

**Comment by ASSAULT-FOX** [comment]
> @ASSAULT-FOX 。。。。。需要你的设备可以访问外网，

可是我本地也没用啊。。。电脑翻墙了

**Comment by iouAkira** [comment]
@ASSAULT-FOX 问题楼上已经跟你说了，你觉得不是这个问题，那就需要你自己踩踩坑去找全原因了。或者放弃tg推送（你电脑翻了不代表你的终端命令行就能翻也不代表你的docker就能翻

**Comment by ASSAULT-FOX** [comment]
> @ASSAULT-FOX 问题楼上已经跟你说了，你觉得不是这个问题，那就需要你自己踩踩坑去找全原因了。或者放弃tg推送（你电脑翻了不代表你的终端命令行就能翻也不代表你的docker就能翻

终端能翻确定了，看输出又像文件哪里不对。再弄不好就放弃tg推送算了

**Comment by nick814** [comment]
tg 推送的user id不是你的账号 是另外方法获得的 你应该是那个user id写的不对

**Comment by ASSAULT-FOX** [comment]
> tg 推送的user id不是你的账号 是另外方法获得的 你应该是那个user id写的不对

我写的是我账号的userid啊，我通过tg里一个叫getuserID的机器人获取的

**Comment by LXK9301** [comment]
> > @ASSAULT-FOX 。。。。。需要你的设备可以访问外网，
> 
> 可是我本地也没用啊。。。电脑翻墙了

。。。。电脑翻了。需要设置代理。IP和端口。自己好好看环境变量合集吧

**Comment by nick814** [comment]
你电脑翻了 那样你能收到tg的消息 你的docker也要翻墙 否则他发不出消息

**Comment by Spock139** [comment]
TG是通过ip通信的，试下将系列ip加入白名单。

67.198.55.0/24

91.108.4.0/22

91.108.8.0/22

91.108.12.0/22

91.108.16.0/22

91.108.20.0/22

91.108.56.0/22

95.161.64.0/20

109.239.140.0/24

149.154.160.0/22

149.154.164.0/22

149.154.168.0/22

149.154.172.0/22

**Comment by ASSAULT-FOX** [comment]
> TG是通过ip通信的，试下将下列ip加入白名单。
> 
> 67.198.55.0/24
> 
> 91.108.4.0/22
> 
> 91.108.8.0/22
> 
> 91.108.12.0/22
> 
> 91.108.16.0/22
> 
> 91.108.20.0/22
> 
> 91.108.56.0/22
> 
> 95.161.64.0/20
> 
> 109.239.140.0/24
> 
> 149.154.160.0/22
> 
> 149.154.164.0/22
> 
> 149.154.168.0/22
> 
> 149.154.172.0/22

请问加入到哪里？电脑的hosts文件里？

**Comment by Spock139** [comment]
> > TG是通过ip通信的，试下将下列ip加入白名单。
> > 67.198.55.0/24
> > 91.108.4.0/22
> > 91.108.8.0/22
> > 91.108.12.0/22
> > 91.108.16.0/22
> > 91.108.20.0/22
> > 91.108.56.0/22
> > 95.161.64.0/20
> > 109.239.140.0/24
> > 149.154.160.0/22
> > 149.154.164.0/22
> > 149.154.168.0/22
> > 149.154.172.0/22
> 
> 请问加入到哪里？电脑的hosts文件里？

不是，强制以上IP走代理，看你扶墙方式，方法不同。

**Comment by ASSAULT-FOX** [comment]
> > > TG是通过ip通信的，试下将下列ip加入白名单。
> > > 67.198.55.0/24
> > > 91.108.4.0/22
> > > 91.108.8.0/22
> > > 91.108.12.0/22
> > > 91.108.16.0/22
> > > 91.108.20.0/22
> > > 91.108.56.0/22
> > > 95.161.64.0/20
> > > 109.239.140.0/24
> > > 149.154.160.0/22
> > > 149.154.164.0/22
> > > 149.154.168.0/22
> > > 149.154.172.0/22
> > 
> > 
> > 请问加入到哪里？电脑的hosts文件里？
> 
> 不是，强制以上IP走代理，看你扶墙方式，方法不同。
> 
> 或者你照大佬的方式，环境变量参数上设置好代理。

好的。那个环境变量我看了，里面好像可以设置tg的代理来着，但是我在设置推送的文件里没看到有这个....
