### ISSUE TITLE
能否将默认区域与执行方式增加为环境变量？

### ISSUE THREAD

**Issue by Tencc** [LXK9301/jd_scripts#21]
## 期望增加的功能

A：请问能否把云函数部署的默认区域和执行方式存为变量？
在云函数环境下，如果选择执行github文件，需要另外付费，而选择执行gitee文件时，多个任务叠加会概率调用失败，而选择执行上传文件可以正常执行，但是这样又无法保持脚本更新，每次更新都需要手动修改部署文件和index。
如果可以修改默认区域和执行方式，每天触发一次自动同步即可，可以更简单的与最新脚本保持同步，希望老哥能考虑一下。

## 入口

A：

**Comment by LXK9301** [comment]
可以了 具体看
https://github.com/LXK9301/jd_scripts/pull/87
