### ISSUE TITLE
docker 跑，日志里没有炸年兽的互助码

### ISSUE THREAD

**Issue by AndrewAndrea** [LXK9301/jd_scripts#213]
这是哪里看，我日志翻了一遍，没有找到

**Comment by AndrewAndrea** [comment]
额，找到了，sharescode.log 没有。jd_nian.log 有

**Comment by andibaby0306** [comment]
export_sharecodes.js  这脚本能读取到所有活动最后一次运行获取到的互助码

**Comment by iclouding** [comment]
@andibaby0306  export_sharecodes.js脚本在哪里？
