### ISSUE TITLE
一直错误

### ISSUE THREAD

**Issue by a136080204** [LXK9301/jd_scripts#215]
开始第1个任务：去达达惊喜提现
去达达惊喜提现[做任务]：ret:1032 retmsg:"err operate env"
任务执行失败，种植的 APP 专属种子，请提供 token 或种植非 APP 种子

==============📣系统通知📣==============
京喜农场
【京东账号1】11111
【水果名称】冰糖橙
任务执行失败，种植的 APP 专属种子，请提供 token 或种植非 APP 种子

**Comment by FanchangWang** [comment]
这中文表达的不够明显吗？让你提供 token 或者种 非 APP 种子

**Comment by s1sunny** [comment]
京喜农场任务执行失败，种植的 APP 专属种子，请提供 token 或种植非 APP 种子是怎么回事呢？京喜农场相信大家都很熟悉，但是京喜农场任务执行失败，种植的 APP 专属种子，请提供 token 或种植非 APP 种子是怎么回事呢，下面就让小编带大家一起了解吧。
　　京喜农场任务执行失败，种植的 APP 专属种子，请提供 token 或种植非 APP 种子，其实就是需要提供 token 或种植非 APP 种子，大家可能会很惊讶京喜农场怎么会任务执行失败，种植的 APP 专属种子，请提供 token 或种植非 APP 种子呢？但事实就是这样，小编也感到非常惊讶。
　　这就是关于京喜农场任务执行失败，种植的 APP 专属种子，请提供 token 或种植非 APP 种子的事情了，大家有什么想法呢，欢迎在评论区告诉小编一起讨论哦！

**Comment by 8839hang** [comment]
这是不认识字？
