### ISSUE TITLE
关于神仙学院的运行报错问题

### ISSUE THREAD

**Issue by ddy4633** [LXK9301/jd_scripts#220]
jd_immortal.js    加了环境变量
## 请在以下补充你需要用到的额外的环境变量，形式：export 变量名="变量值"
export JD_IMMORTAL_LATLON={"lat":23.119172, "lng":113.373756}

![京东](https://user-images.githubusercontent.com/31069404/105573435-830cd300-5d98-11eb-9de1-94a6554b5da1.png)

请大佬看看哪里错了

**Comment by EvineDeng** [comment]
@ddy4633 仔细读注释，一个符号都不要漏，另外：你提错地方了
