### ISSUE TITLE
怎么运行在GitHub或者腾讯云函数,哪位大佬提示下

### ISSUE THREAD

**Issue by mynameisSB** [LXK9301/jd_scripts#221]

**Comment by beenewtree** [comment]
不要在github上运行了，云函数库里有操作说明

**Comment by mynameisSB** [comment]
> 不要在github上运行了，云函数库里有操作说明

在哪里,我没看见,能教教我吗,大佬

**Comment by beenewtree** [comment]
@mynameisSB 自己去找，如果找不到我建议你也不要折腾云函数了，还是老老实实的在手机上跑吧

**Comment by mynameisSB** [comment]
> @mynameisSB自己去找，如果找到我建议你也不要折腾云函数了，还是老老实实的在手机上跑吧

好吧
