### ISSUE TITLE
云函数一键部署Action报错

### ISSUE THREAD

**Issue by yogayyy** [LXK9301/jd_scripts#223]
上一次自动部署是三天前，今天同步了最新的库后重新部署开始报错，看进程好像是文件上传没进度，最终执行完报错：大佬，Process completed with exit code 1；

环境变量没有变化，之前部署的云函数也提前删除了👀我搜了一下好像老库有同样的issues...可惜看不了😂有大佬知道什么原因吗？
![30D2E7D6-B332-4B1A-A0D4-2CFC6BF26B9C](https://user-images.githubusercontent.com/50315632/105576496-0ab10c80-5dae-11eb-9c81-347d8595f1ba.jpeg)

**Comment by syouko** [comment]
请勿使用github action、滥用github资源会封我仓库以及账号，如再被封，则金盆洗手。详见
不知道你这样使用AC部署到其他地方算不算滥用AC

**Comment by DoveBoy** [comment]
@syouko deploy tencentscf并没有schedule，主要原因不是这个

**Comment by charleyyy** [comment]
我也遇到这个 时好时坏 有时可以同步有时不行

**Comment by charleyyy** [comment]
不知道是不是云函数升级导致的
https://cloud.tencent.com/document/product/583/51773
SCF 日志服务升级详情
自2021年01月29日起，新建函数如未指定日志投递主题将使用默认投递日志能力，函数调用日志将按照函数日志配置投递到指定主题。
默认投递日志时，SCF 将会为您开通日志服务并将函数调用日志投递至 SCF 专用日志集下的日志主题中，SCF 专用日志集和日志主题分别以 SCF_logset 和 SCF_logtopic 为前缀命名，如不存在将自动创建。函数调用日志默认保留 7 天，您可在 日志服务控制台 查看及管理。
腾讯云日志服务 CLS 商业化后，腾讯云仍旧为所有用户在每个地域提供一定量的免费额度，SCF 专用日志主题将会占用该免费额度，日志计费详情请参见 CLS 计费指引。
在发布窗口期（2021年01月25日 - 2021年01月29日）SCF 投递至 CLS 的日志格式将按地域逐步调整，更新后的日志格式请参见 操作指引文档，相比于当前投递到 CLS 的函数日志格式，增加了字段 SCF_LogTime，SCF_Duration，SCF_MemUsage，SCF_StatusCode 和 SCF_RetryNum，下线了字段 SCF_Index。
SCF 日志接入 CLS 后，依然为异步调用的函数保留返回数据。返回数据将写入 SCF_Message，格式为 Response RequestId:xxx RetMsg:xxx 。

**Comment by yogayyy** [comment]
已修复，终结。
感谢🐺仔～

**Comment by charleyyy** [comment]
> 已修复，终结。
> 感谢🐺仔～

你好 新的方法会同步过去定时触发和环境变量么？我删除原来的函数后变量同步不过去了...

**Comment by yogayyy** [comment]
@charleyyy 可以啊，你同步最新的库在试试吧

charleyyy <notifications@github.com>于2021年1月25日 周一00:03写道：
