### ISSUE TITLE
环境变量上传不全

### ISSUE THREAD

**Issue by luovivi** [LXK9301/jd_scripts#228]
serets里的变量上传TX云每次都缺少cookie和两个自定义UA，是否因为字符过长导致的失败呢？
![屏幕截图 2021-01-24 171005](https://user-images.githubusercontent.com/28199077/105625978-0812ed80-5e68-11eb-9b3a-7635f1203d1d.png)

**Comment by lovelonger** [comment]
叫你们别用ac跑，就是不听

**Comment by littleip** [comment]
腾讯云环境变量设置不能超过4K

**Comment by luovivi** [comment]
> 腾讯云环境变量设置不能超过4K

查看日志发现问题不是出在上传过程，是在初始化变量的过程，不知道是什么问题。
另外手动去TX云设置环境变量是可以的。
![屏幕截图 2021-01-25 121359](https://user-images.githubusercontent.com/28199077/105660895-051b0a00-5f07-11eb-86f3-19a56aa6cbc9.png)

**Comment by q4w5e6** [comment]
> > 腾讯云环境变量设置不能超过4K
> 
> 查看日志发现问题不是出在上传过程，是在初始化变量的过程，不知道是什么问题。
> 另外手动去TX云设置环境变量是可以的。
> ![屏幕截图 2021-01-25 121359](https://user-images.githubusercontent.com/28199077/105660895-051b0a00-5f07-11eb-86f3-19a56aa6cbc9.png)

不能有空格，回车。

**Comment by abcdol** [comment]
> 腾讯云环境变量设置不能超过4K

本地上传的时候直接修改serverless.yml好像没有这个限制，请问有相关参考链接吗？
