### ISSUE TITLE
互助码上传api

### ISSUE THREAD

**Issue by nbzongzong** [LXK9301/jd_scripts#23]
老的互助码上传api关闭了，新地址貌似也关闭了上传接口，有大佬能告诉我如何上传自己的互助码么？

**Comment by hengwuming** [comment]
只能tg机器人上传了

**Comment by testonlys** [comment]
> 
> 
> 只能tg机器人上传了
能告知下 tg机器 号吗？

**Comment by hengwuming** [comment]
> > 只能tg机器人上传了
> > 能告知下 tg机器 号吗？谢谢

我也不知道.....

**Comment by iouAkira** [comment]
@hengwuming 建议照顾定好友互助
