### ISSUE TITLE
云函数部署报错

### ISSUE THREAD

**Issue by Vincentzhengwei** [LXK9301/jd_scripts#254]
@shylocks 云函数部署报错，但是我的secrets是配置了TENCENT_FUNCTION_NAME的。
![image](https://user-images.githubusercontent.com/32627913/105792589-a4e99e00-5fc2-11eb-84cd-63d0fd859d48.png)

另外，好奇心态问下，为什么不使用原来的sls deploy部署代码，要先进行压缩，再上传到云函数的形式？ 我昨天本地是可以执行这个操作的

**Comment by LXK9301** [comment]
云函数升级了，还有重新去看教程搞

readme 已经去掉云函数的入口了，不进行解答这方面的问题

**Comment by Vincentzhengwei** [comment]
> 云函数升级了，重新去看教程操作
> 
> readme 已经去掉云函数的入口了，不进行解答这方面的问题

我已经看过教程了，教程要更新的内容也更新了，我在代码上评论了，其他人也有相同的情况，不仅仅是我的问题

**Comment by iouAkira** [comment]
@shylocks pr改了部署方式，等他处理或者自己调整为以前版本是可以正常部署的。

**Comment by 475488889** [comment]
现在的教程在那个地方呀

**Comment by raindew517** [comment]
serverless deploy 部署完全没问题的

**Comment by qiandaoniaoren** [comment]
同样的问题 该增加的值都增加了

**Comment by Vincentzhengwei** [comment]
> 同样的问题 该增加的值都增加了

@LXK9301 不是我一个人这个问题，请大佬帮忙看看。都是看了新的教程增加了对应的配置值
