### ISSUE TITLE
京喜APP活动提示爆满解决方法

### ISSUE THREAD

**Issue by Misaka09982** [LXK9301/jd_scripts#255]
这两天手里有两个黑号分别购买了一件商品，第二天便发现京喜农场选了种子种植了，去了工厂也可以选东西生产，询问了号主说是买了50块以上的商品，具体要多少钱的商品才能解除，大家试试

**Comment by fengmikaelson** [comment]
我有一个号什么活动都能参加，就是参加不了疯狂的joy。。

**Comment by xiaokaig** [comment]
那还是黑着吧🧐
