### ISSUE TITLE
关于云函数SCF_REGION

### ISSUE THREAD

**Issue by lpk92** [LXK9301/jd_scripts#256]
SCF_REGION这一块我在腾讯云查不到相关资料。大佬能教一下吗？现在不能同步部署到云函数了

**Comment by q4w5e6** [comment]
-:  region: "ap-hongkong",
  +:  region: process.env.TENCENT_REGION, // 区域参考，https://cloud.tencent.com/document/product/213/6091

**Comment by q4w5e6** [comment]
> SCF_REGION这一块我在腾讯云查不到相关资料。大佬能教一下吗？现在不能同步部署到云函数了

[区域参考](https://www.cloud.tencent.com/document/product/213/6091)
