### ISSUE TITLE
京喜工厂部分用户执行报错

### ISSUE THREAD

**Issue by x91270** [LXK9301/jd_scripts#258]
挂了4个号 ，其中有两个，无法正常收取电力 和  偷取好友零件，但实际在客户端操作正常

【京东账号3 的京喜工厂好友互助码】
已投入电力：152200
所需电力：570000
生产进度：26.70%
【今日招工进度】5/10
今日助力好友机会已耗尽

nextCollectDoubleFlag::1
nextCollectDoubleType::1

下次集满收取可双倍电力
发电机：当前 37 电力，最大值 360 电力
去做任务：[限时]仅需5人瓜分1.5万电
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取[限时]仅需5人瓜分1.5万电任务奖励失败，任务已领奖
去做任务：[限时]仅需5人瓜分1.5万电
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取[限时]仅需5人瓜分1.5万电任务奖励失败，任务已领奖
去做任务：上集市做调研30s
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取上集市做调研30s任务奖励失败，任务已领奖
去做任务：上集市做调研30s
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取上集市做调研30s任务奖励失败，任务已领奖
去做任务：去集市发现5件好物
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集市发现5件好物任务奖励失败，任务已领奖
去做任务：去集市发现5件好物
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集市发现5件好物任务奖励失败，任务已领奖
去做任务：去集市发现5件好物
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集市发现5件好物任务奖励失败，任务已领奖
去做任务：去集市发现5件好物
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集市发现5件好物任务奖励失败，任务已领奖
去做任务：去集市发现5件好物
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集市发现5件好物任务奖励失败，任务已领奖
去做任务：去集市发现5件好物
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集市发现5件好物任务奖励失败，任务已领奖
去做任务：开宝箱找安全帽
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取开宝箱找安全帽任务奖励失败，任务已领奖
去做任务：开宝箱找安全帽
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取开宝箱找安全帽任务奖励失败，任务已领奖
去做任务：去签到，可领现金提现
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去签到，可领现金提现任务奖励失败，任务已领奖
去做任务：去签到，可领现金提现
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去签到，可领现金提现任务奖励失败，任务已领奖
去做任务：去玩炸年兽分10亿
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去玩炸年兽分10亿任务奖励失败，任务已领奖
去做任务：去玩炸年兽分10亿
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去玩炸年兽分10亿任务奖励失败，任务已领奖
去做任务：去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！,去京东看年货清单
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！,去京东看年货清单任务奖励失败，任务已领奖
去做任务：去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！,去京东看年货清单
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！,去京东看年货清单任务奖励失败，任务已领奖
去做任务：去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！,去京东看年货清单
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！,去京东看年货清单任务奖励失败，任务已领奖
去做任务：去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！,去京东看年货清单
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！,去京东看年货清单任务奖励失败，任务已领奖
去做任务：去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！,去京东看年货清单
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！,去京东看年货清单任务奖励失败，任务已领奖
去做任务：上岛兑0元好物,逛农场免费领水果,出海寻宝领100元红包
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取上岛兑0元好物,逛农场免费领水果,出海寻宝领100元红包任务奖励失败，任务已领奖
去做任务：上岛兑0元好物,逛农场免费领水果,出海寻宝领100元红包
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取上岛兑0元好物,逛农场免费领水果,出海寻宝领100元红包任务奖励失败，任务已领奖
去做任务：上岛兑0元好物,逛农场免费领水果,出海寻宝领100元红包
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取上岛兑0元好物,逛农场免费领水果,出海寻宝领100元红包任务奖励失败，任务已领奖
去做任务：上岛兑0元好物,逛农场免费领水果,出海寻宝领100元红包
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取上岛兑0元好物,逛农场免费领水果,出海寻宝领100元红包任务奖励失败，任务已领奖
完成任务：共领取0电力
投入失败，电力不足，快去做任务吧~
打工电力：收取失败，活动火爆，请稍后再试~
打工电力：收取失败，活动火爆，请稍后再试~
收自己地下零件失败：好可惜,没中奖哦~,直接跳出
今日收取零件已达上限，偷好友零件也达到上限，故跳出

**Comment by LXK9301** [comment]
不用你发现。这问题很早就有了
