### ISSUE TITLE
京喜工厂无法执行

### ISSUE THREAD

**Issue by gnowmil** [LXK9301/jd_scripts#260]
其他脚本运行正常，京喜工厂运行出现如下日志：

🔔京喜工厂, 开始!
您的cookie选择的是用&隔开

====================共有5个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/1/26 下午8:54:28=====================

开始获取京喜工厂配置文件

tuanActiveId: TvjO5k4gaVqVHMRJIogd_g==
您的互助码选择的是用&隔开

共0个京东账号

您提供了5个账号的京喜工厂助力码

==============📣系统通知📣==============
京喜工厂
【提示】请先获取京东账号一cookie
直接使用NobyDa的京东签到获取
https://bean.m.jd.com/bean/signIndex.action

🔔京喜工厂, 结束! 🕛 0.489 秒

**Comment by LXK9301** [comment]
自己设置了不该设置的东西
