### ISSUE TITLE
神仙学院答题

### ISSUE THREAD

**Issue by ddy4633** [LXK9301/jd_scripts#270]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] Docker1 
- [x ] Docker2 
- [ ] 系统直装 
- [ ] iOS代理软件

### (1) 具体问题
A：
直接执行报错

### (2) 详细日志
A：
![image](https://user-images.githubusercontent.com/31069404/105952319-629c8b80-60ac-11eb-9b21-45a6f4e3a425.png)

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by iyzgit** [comment]
同样错误。

**Comment by qingcher** [comment]
新更新的题库，filter定义识别不了@

**Comment by Moy4e** [comment]
同样的错误。。期待修复。。

**Comment by Lunrry** [comment]
答题脚本有误，本地执行报错，但是能够运行，只是无法找到正确答案，腾讯云执行超时，无法运行（表现在积分积分无改变）

**Comment by 9k001** [comment]
插眼

**Comment by qq337829302** [comment]
http://qn6l5d6wm.hn-bkt.clouddn.com/question.json  显示document not found

**Comment by Moy4e** [comment]
刚试了一下，已经修复了，各位试试啊。

**Comment by shylocks** [comment]
fixed
