### ISSUE TITLE
项目呢？什么情况？

### ISSUE THREAD

**Issue by SuperManito** [LXK9301/jd_scripts#282]
EvineDeng的jd-base也无法访问了

**Comment by happyzjhao** [comment]
![image](https://user-images.githubusercontent.com/56525354/105994068-179d6b00-60e2-11eb-9cad-54e989b8000f.png)

**Comment by Yvan0329** [comment]
什么情况，，

**Comment by SuperManito** [comment]
@happyzjhao 那什么地方还能用？云主机？函数？
