### ISSUE TITLE
关于此新仓库

### ISSUE THREAD

**Issue by LXK9301** [LXK9301/jd_scripts#3]
原来github账号被间接封了，jd_scripts仓库当然也就没了，具体原因不明。

猜测是部分使用github action运行脚本滥用github资源导致。

故希望请勿使用上述方法食用。

原账号：https://github.com/lxk0301

原仓库：https://github.com/lxk0301/jd_scripts
外界查看已显示404了，
我自己查看如下图效果(注意顶部红色英文)：
![2EC7497C-1EE0-4247-B0BA-78B58CA3EB2A](https://user-images.githubusercontent.com/72646373/104809331-80096400-5827-11eb-85e4-018030faf8cc.png)

**Comment by Mr-zhaohy** [comment]
前排支持，拒绝ac

**Comment by chengkni** [comment]
已经在自己的docker呼应上了。感谢大佬的项目！

**Comment by fckcg** [comment]
希望各位耗子尾汁

**Comment by Silentely** [comment]
各位ac党耗子尾汁，用云函数、docker不香么

**Comment by JohnED512** [comment]
发现用ac的我肯定举报

**Comment by sgzman** [comment]
在脚本上加上禁止ac的代码，防止小白

**Comment by sgzman** [comment]
在脚本上加上禁止ac的代码，防止小白

**Comment by dodoeye** [comment]
想到个消fork的办法，就是lxk大佬把仓库设为私有，然后再重新公开，就会丢失fork，不过也会丢失所有watch和star……

**Comment by Silentely** [comment]
> 想到个消fork的办法，就是lxk大佬把仓库设为私有，然后再重新公开，就会丢失fork，不过也会丢失所有watch和star……

但是你这个也有问题 你是打算每到100个fork就设置私有么？

**Comment by xiami2156** [comment]
已打赏，感谢大佬的付出。

**Comment by Ca11back** [comment]
云函数调用raw太多会不会也有影响呢?

**Comment by dodoeye** [comment]
> > 想到个消fork的办法，就是lxk大佬把仓库设为私有，然后再重新公开，就会丢失fork，不过也会丢失所有watch和star……
> 
> 但是你这个也有问题 你是打算每到100个fork就设置私有么？

如果被fork速度快确实不方便。不知道仓库可见设置能不能自动化，还是只能手动

**Comment by LXK9301** [comment]
> 云函数调用raw太多会不会也有影响呢?

应该无事。

**Comment by LXK9301** [comment]
> 已打赏，感谢大佬的付出。

多谢🙏

**Comment by LXK9301** [comment]
> 想到个消fork的办法，就是lxk大佬把仓库设为私有，然后再重新公开，就会丢失fork，不过也会丢失所有watch和star……

fork倒还好。别用action即可。

**Comment by Ca11back** [comment]
> > 云函数调用raw太多会不会也有影响呢?
> 
> 应该无事。

我也打赏了,感谢大佬付出.
我是最近才刚刚发现这个项目,看到前两天readme云函数方法已经取消了,如果不因为调用raw有影响的话,请问云函数教程为什么取消了?我还以为会有影响,特意把云函数都改成运行上传了.......

**Comment by Mezone** [comment]
买个玩客云30多块钱，刷armbian 在家跑着脚本 真香

**Comment by chihwell** [comment]
> > > 云函数调用raw太多会不会也有影响呢?
> > 
> > 
> > 应该无事。
> 
> 我也打赏了,感谢大佬付出.
> 我是最近才刚刚发现这个项目,看到前两天readme云函数方法已经取消了,如果不因为调用raw有影响的话,请问云函数教程为什么取消了?我还以为会有影响,特意把云函数都改成运行上传了.......

感觉云函数跑本地脚本挺好的，只要勤快点更新就行，这样有利于保护大佬的仓库

**Comment by 465509522** [comment]
这个库不是不能用ac吗？

**Comment by a3253933** [comment]
原来的群晖docker1的使用方法还能这样安装吗？还是说出了其他的，我看了wiki里什么也没写

**Comment by ATIAboo** [comment]
repo sync的方式也不可以了吗？

**Comment by 150154906** [comment]
紧跟大佬的足迹...

**Comment by JohnED512** [comment]
> > 云函数调用raw太多会不会也有影响呢?
> 
> 应该无事。

大佬我记得之前有个issues里提到过云函数本地运行的方法(index.js里的)能不能重新发一下，感谢

**Comment by creazy412** [comment]
搞个二手树莓派来跑也很简单.

**Comment by qingxiwa** [comment]
难怪这两天群晖签到不推送了😒

**Comment by dyl1290722515** [comment]
使用圈X的路过，我原来也是用AC，但是看到大佬的公告，就油管看视频研究一下，不会的朋友们可以学一学，圈X上手了还是很好用的

**Comment by laycher** [comment]
>  sync的方式也不可以了吗？

同问，这种方式可行不？

**Comment by z844911398** [comment]
> 买个玩客云30多块钱，刷armbian在家跑着脚本真香

玩客云咋操作的，正好家里有一个

**Comment by Mezone** [comment]
> > 买个玩客云30多块钱，刷armbian在家跑着脚本真香
> 
> 玩客云咋操作的，正好家里有一个

恩山找教程，刷armbian， 装nodejs跑

**Comment by sgzman** [comment]
> > > 买个玩客云30多块钱，刷armbian在家跑着脚本真香
> > 
> > 
> > 玩客云咋操作的，正好家里有一个
> 
> 恩山找教程，刷armbian， 装nodejs跑

和docker差不多不？自动更新

**Comment by hupo376787** [comment]
禁止Fork🈲

**Comment by hupo376787** [comment]
下载下来代码，上传到自己仓库下，执行自己的actions，应该没问题。
缺点就是不能同步代码，需要手动更新

**Comment by EvineDeng** [comment]
> 下载下来代码，上传到自己仓库下，执行自己的actions，应该没问题。
> 缺点就是不能同步代码，需要手动更新


仍然有风险的，因为和此仓库仍然有关联，所以不要这么干。几十块买个arm设备玩docker不贵。

**Comment by Mezone** [comment]
> 更新

可以自动更新的  或者自己安装docker也可以

**Comment by Mezone** [comment]
> > > > 买个玩客云30多块钱，刷armbian在家跑着脚本真香
> > > 
> > > 
> > > 玩客云咋操作的，正好家里有一个
> > 
> > 
> > 恩山找教程，刷armbian， 装nodejs跑
> 
> 和docker差不多不？自动更新

可以自动更新的 或者自己安装docker也可以

**Comment by hupo376787** [comment]
> > 下载下来代码，上传到自己仓库下，执行自己的actions，应该没问题。
> > 缺点就是不能同步代码，需要手动更新
> 
> 仍然有风险的，因为和此仓库仍然有关联，所以不要这么干。几十块买个arm设备玩docker不贵。

那就只能用我的树莓派跑了

**Comment by sgzman** [comment]
> > > 下载下来代码，上传到自己仓库下，执行自己的actions，应该没问题。
> > > 缺点就是不能同步代码，需要手动更新
> > 
> > 
> > 仍然有风险的，因为和此仓库仍然有关联，所以不要这么干。几十块买个arm设备玩docker不贵。
> 
> 那就只能用我的树莓派跑了

我对树莓派还是挺感兴趣的，哈哈

**Comment by wudongdefeng** [comment]
大佬可以设置个云函数，每天定时23:50，仓库设置为私有，然后公开，就可以预防fork和star

**Comment by iplcdn** [comment]
能不能搞到软路由openwrt插件运行？就是类似于京东签到插件那样子可以编译进去op

**Comment by z844911398** [comment]
> > > > > 买个玩客云30多块钱，刷armbian在家跑着脚本真香
> > > > 
> > > > 
> > > > 玩客云咋操作的，正好家里有一个
> > > 
> > > 
> > > 恩山找教程，刷armbian，装nodejs跑
> > 
> > 
> > 和docker差不多不？自动更新
> 
> 可以自动更新的或自己安装docker也可以

收到！

**Comment by google-mirror** [comment]
可以用windows计划任务

**Comment by 412273066** [comment]
感谢大佬

**Comment by zhanggaolei001** [comment]
某度云主机首年50多块钱,我撸了一个,感觉还是挺方便的.
家里有退役的安卓手机,有没有小伙伴折腾过,可否老骥伏枥再战几年?

**Comment by Clown666** [comment]
刚接触这个项目，请问怎么可以部署到云函数，可以简单介绍一下嘛

**Comment by benz819** [comment]
应该是actions运行有时候会报错，然后默认系统会发邮件通知用户，太多了肯定被ban了，我之前用都在设置里取消错误邮件通知的。

**Comment by LXK9301** [comment]
@benz819 和邮件通知无关

**Comment by sgzman** [comment]
> 某度云主机首年50多块钱,我撸了一个,感觉还是挺方便的.
> 家里有退役的安卓手机,有没有小伙伴折腾过,可否老骥伏枥再战几年?

这个可以的，有链接吗？

**Comment by Deskyo** [comment]
> 
> 
> 刚接触这个项目，请问怎么可以部署到云函数，可以简单介绍一下嘛

同想问一下，就差最后一步怎么部署到腾讯云函数了QWQ

**Comment by yhboss** [comment]
> 已经在自己的docker呼应上了。感谢大佬的项目！

分享一下你的docker，谢谢~~

**Comment by chengkni** [comment]
> > 已经在自己的docker呼应上了。感谢大佬的项目！
> 
> 分享一下你的docker，谢谢~~

这个项目的docker目录下边就是大佬给的容器构建文件
而且建议使用docker-compose。
https://github.com/LXK9301/jd_scripts/blob/master/docker/Readme.md
可以看一下大佬的Readme。里边很详细的文档。

**Comment by Ca11back** [comment]
> 某度云主机首年50多块钱,我撸了一个,感觉还是挺方便的.
> 家里有退役的安卓手机,有没有小伙伴折腾过,可否老骥伏枥再战几年?

废andoird手机要是装能ubuntu touch估计还真能跟主机一样用吧

**Comment by 428255177** [comment]
> 玩客云3
哪里30多能买个玩客云

**Comment by qxy0789** [comment]
云函数跑本地脚本，每天晚上11点多更新上传一次脚本包

**Comment by doudou628** [comment]
> 云函数跑本地脚本，每天晚上11点多更新上传一次脚本包

大佬 是手动上传的吗

**Comment by sgzman** [comment]
> > 玩客云3
> > 哪里30多能买个玩客云

同问啊   可以搞个来玩玩

**Comment by Niddl** [comment]
> > > 玩客云3
> 
> > > 哪里30多能买个玩客云
> 
> 
> 
拼多多> 同问啊   可以搞个来玩玩

**Comment by loyio** [comment]
不都是用qx和Surge吗

**Comment by 4eszxcvgy7** [comment]
> 各位ac党耗子尾汁，用云函数、docker不香么

我等小白有什么办法，家里N1也有，软路由也有，不会玩啊，知道这是大神大作也不会用，教程看了一个月，出了看断片，啥都不懂，想学docker，教程都是从是从什么是docker云云开始，要么就是敲代码，小白也为难，什么是ac操作，根本不懂

**Comment by JohnED512** [comment]
@4eszxcvgy7 n1不好玩卖给我吧

**Comment by DoveBoy** [comment]
@4eszxcvgy7 实在看不懂也没办法，建议Ctrl+w

**Comment by 4eszxcvgy7** [comment]
> @4eszxcvgy7 n1不好玩卖给我吧

我两个看电视，两个闲置了，但是不好卖，我买的尸体自己修好的，顺便阔了个容，32G但是在吃灰，想薅点狗毛，但是装了OP按照教程到了http://192.168.6.1:9999/#!/home这个界面就根本不知道怎么弄了，大神教程有，但是都比较跳脱，第一次接触的人根本没法下手

**Comment by JohnED512** [comment]
@4eszxcvgy7 这是哪个服务

**Comment by 4eszxcvgy7** [comment]
> @4eszxcvgy7 这是哪个服务

不懂你意思

**Comment by bluewatercg** [comment]
> > @4eszxcvgy7 n1不好玩卖给我吧
> 
> 我两个看电视，两个闲置了，但是不好卖，我买的尸体自己修好的，顺便阔了个容，32G但是在吃灰，想薅点狗毛，但是装了OP按照教程到了[http://192.168.6.1:9999/#!/home这个界面就根本不知道怎么弄了，大神教程有，但是都比较跳脱，第一次接触的人根本没法下手](http://192.168.6.1:9999/#!/home%E8%BF%99%E4%B8%AA%E7%95%8C%E9%9D%A2%E5%B0%B1%E6%A0%B9%E6%9C%AC%E4%B8%8D%E7%9F%A5%E9%81%93%E6%80%8E%E4%B9%88%E5%BC%84%E4%BA%86%EF%BC%8C%E5%A4%A7%E7%A5%9E%E6%95%99%E7%A8%8B%E6%9C%89%EF%BC%8C%E4%BD%86%E6%98%AF%E9%83%BD%E6%AF%94%E8%BE%83%E8%B7%B3%E8%84%B1%EF%BC%8C%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%8E%A5%E8%A7%A6%E7%9A%84%E4%BA%BA%E6%A0%B9%E6%9C%AC%E6%B2%A1%E6%B3%95%E4%B8%8B%E6%89%8B)

怎么扩容的，接个U盘不行吗

**Comment by 4eszxcvgy7** [comment]
> > > @4eszxcvgy7 n1不好玩卖给我吧
> > 
> > 
> > 我两个看电视，两个闲置了，但是不好卖，我买的尸体自己修好的，顺便阔了个容，32G但是在吃灰，想薅点狗毛，但是装了OP按照教程到了[http://192.168.6.1:9999/#!/home这个界面就根本不知道怎么弄了，大神教程有，但是都比较跳脱，第一次接触的人根本没法下手](http://192.168.6.1:9999/#!/home%E8%BF%99%E4%B8%AA%E7%95%8C%E9%9D%A2%E5%B0%B1%E6%A0%B9%E6%9C%AC%E4%B8%8D%E7%9F%A5%E9%81%93%E6%80%8E%E4%B9%88%E5%BC%84%E4%BA%86%EF%BC%8C%E5%A4%A7%E7%A5%9E%E6%95%99%E7%A8%8B%E6%9C%89%EF%BC%8C%E4%BD%86%E6%98%AF%E9%83%BD%E6%AF%94%E8%BE%83%E8%B7%B3%E8%84%B1%EF%BC%8C%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%8E%A5%E8%A7%A6%E7%9A%84%E4%BA%BA%E6%A0%B9%E6%9C%AC%E6%B2%A1%E6%B3%95%E4%B8%8B%E6%89%8B)
> 
> 怎么扩容的，接个U盘不行吗



> > > @4eszxcvgy7 n1不好玩卖给我吧
> > 
> > 
> > 我两个看电视，两个闲置了，但是不好卖，我买的尸体自己修好的，顺便阔了个容，32G但是在吃灰，想薅点狗毛，但是装了OP按照教程到了[http://192.168.6.1:9999/#!/home这个界面就根本不知道怎么弄了，大神教程有，但是都比较跳脱，第一次接触的人根本没法下手](http://192.168.6.1:9999/#!/home%E8%BF%99%E4%B8%AA%E7%95%8C%E9%9D%A2%E5%B0%B1%E6%A0%B9%E6%9C%AC%E4%B8%8D%E7%9F%A5%E9%81%93%E6%80%8E%E4%B9%88%E5%BC%84%E4%BA%86%EF%BC%8C%E5%A4%A7%E7%A5%9E%E6%95%99%E7%A8%8B%E6%9C%89%EF%BC%8C%E4%BD%86%E6%98%AF%E9%83%BD%E6%AF%94%E8%BE%83%E8%B7%B3%E8%84%B1%EF%BC%8C%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%8E%A5%E8%A7%A6%E7%9A%84%E4%BA%BA%E6%A0%B9%E6%9C%AC%E6%B2%A1%E6%B3%95%E4%B8%8B%E6%89%8B)
> 
> 怎么扩容的，接个U盘不行吗

我也不清楚接u盘除了多占用一个USB外和扩容有没有区别，扩容要换芯片，要工具和手艺
我这个网页进来图片都显示不出来是正常的吗？纯小白，第一次接触这个网站

**Comment by 3136083906** [comment]
希望能坚持久一点吧，大家好自为之，且行且珍惜。

**Comment by zengxiangj** [comment]
https://github.com/lifeishard4me/Actions
这个项目在跑actions，还蛮多人在用

**Comment by tommyhe1217** [comment]
> 各位ac党耗子尾汁，用云函数、docker不香么

估计是不会吧，我自己好不容易搞定云函数，docker就是不会，虽然现在云函数同步不了，但是我还是响应拒绝AC，不给大佬添麻烦

**Comment by dodoeye** [comment]
> https://github.com/lifeishard4me/Actions
> 这个项目在跑actions，还蛮多人在用

这个ac调用的是gitlab上的镜像

**Comment by Deskyo** [comment]
> > 各位ac党耗子尾汁，用云函数、docker不香么
> 
> 估计是不会吧，我自己好不容易搞定云函数，docker就是不会，虽然现在云函数同步不了，但是我还是响应拒绝AC，不给大佬添麻烦

请问能否简要告知一下用云函数运行本地代码的设置步骤，就差最后一步了233

**Comment by sgzman** [comment]
> > 各位ac党耗子尾汁，用云函数、docker不香么
> 
> 估计是不会吧，我自己好不容易搞定云函数，docker就是不会，虽然现在云函数同步不了，但是我还是响应拒绝AC，不给大佬添麻烦

其实也不难的，我之前是在windows上的linux子系统跑的，后来又买的云服务器，在上面跑。不怕不会，就怕不去尝试。

**Comment by sgzman** [comment]
> > 某度云主机首年50多块钱,我撸了一个,感觉还是挺方便的.
> > 家里有退役的安卓手机,有没有小伙伴折腾过,可否老骥伏枥再战几年?
> 
> 废andoird手机要是装能ubuntu touch估计还真能跟主机一样用吧

昨天搞了一天，终于把我的魅族MX4给装上了ubuntu touch。哈哈

**Comment by ccboxjole** [comment]
> > 玩客云3
> > 哪里30多能买个玩客云

现在基本上都是30多不包邮呀，成色我觉得无所谓，刷armbian跑大佬的脚本非常不错，还能装宝塔玩

**Comment by Niddl** [comment]
@ccboxjole 拼多多40包邮 v1.3刷机专用

**Comment by scllen** [comment]
死亡倒计时，又快1千fork了

**Comment by koast18** [comment]
> 使用圈X的路过，我原来也是用AC，但是看到大佬的公告，就油管看视频研究一下，不会的朋友们可以学一学，圈X上手了还是很好用的

圈X是什么，虽然本地有机器跑，但是还是很好奇。

**Comment by Niddl** [comment]
@koast18 建议谷歌哦

**Comment by iplcdn** [comment]
外区appstore的QuantumultX

**Comment by sgzman** [comment]
> > 使用圈X的路过，我原来也是用AC，但是看到大佬的公告，就油管看视频研究一下，不会的朋友们可以学一学，圈X上手了还是很好用的
> 
> 圈X是什么，虽然本地有机器跑，但是还是很好奇。

圈X我也有，不过我还是买了云服务器

**Comment by qianx443** [comment]
看来楼上的，准备回家折腾下闲置的玩客云，目前vps上面跑的docker，有点浪费

**Comment by y785201595** [comment]
fatal: Authentication failed for 'https://github.com/EvineDeng/jd-base/'
error: Could not fetch origin
HEAD is now at e24bb7b shylocks/Loon仓库被封，暂时屏蔽掉相关代码。

shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...
估计凉了

**Comment by EvineDeng** [comment]
@y785201595

**Comment by y785201595** [comment]
> @y785201595 是我jd-base删库了。
> 
> ![image](https://user-images.githubusercontent.com/30263136/105989842-a4ddc100-60dc-11eb-9b0c-5f83c2ad271e.png)

感谢大佬一直以来的付出

**Comment by wrisin** [comment]
> @y785201595 是我jd-base删库了。
> 
> ![image](https://user-images.githubusercontent.com/30263136/105989842-a4ddc100-60dc-11eb-9b0c-5f83c2ad271e.png)

感谢大佬的付出，期待大佬的复出。
