### ISSUE TITLE
京东新年活动js圈x图标

### ISSUE THREAD

**Issue by yogayyy** [LXK9301/jd_scripts#34]
## 期望增加的功能

A：
老大京东新年相关的活动好像都没做圈x的图标，随手做了一下，供需要的人使用吧👀风格比较统一，放在一起更加美观哦。

# 京东炸年兽
0 0/1 * * * https://raw.githubusercontent.com/LXK9301/jd_scripts/master/jd_nian.js, tag=京东炸年兽, img-url=https://raw.githubusercontent.com/yogayyy/Scripts/main/Icon/lxk0301/jd_nian.png, enabled=true
# 领爆竹
20 * * * * https://raw.githubusercontent.com/LXK9301/jd_scripts/master/jd_nianCollect.js, tag=京东炸年兽领爆竹, img-url=https://raw.githubusercontent.com/yogayyy/Scripts/main/Icon/lxk0301/jd_nianCollect.png, enabled=true
# 年货节（2.9结束）
1 7 * * * https://raw.githubusercontent.com/LXK9301/jd_scripts/master/jd_nh.js, tag=京东年货节, img-url=https://raw.githubusercontent.com/yogayyy/Scripts/main/Icon/shylocks/jdnh.png, enabled=true

效果如图：
![70D38BD2-3BC9-4573-8042-9917A0F75543](https://user-images.githubusercontent.com/50315632/104867509-fe771a80-597b-11eb-997a-e098fe68cb57.jpeg)

## 入口

A：

**Comment by dyl1290722515** [comment]
已使用，很不错，赞一个

**Comment by rewardhunter066** [comment]
太棒了，感谢，已使用！
