### ISSUE TITLE
企业微信推送@不同用户

### ISSUE THREAD

**Issue by AboutCXJ** [LXK9301/jd_scripts#35]
## 期望增加的功能
A：企业微信推送，根据不同账号，在群里@不同用户

**Comment by iouAkira** [comment]
@AboutCXJ 这是方便代挂吗？

**Comment by AboutCXJ** [comment]
> @AboutCXJ 这是方便代挂吗？

嗯嗯，帮朋友挂账号，每次要通知他们，比较麻烦

**Comment by qiangxinglin** [comment]
推送加可以实现(pushplus), 把他们各自开一个单人群组即可, 用多个`PUSH_PLUS_USER`通知

**Comment by hclasmn** [comment]
目前只能分开compose去推送，让他们关注企业微信，其他不变，ID改掉就只推送给那个人了

**Comment by chanho0** [comment]
> 推送加可以实现(pushplus), 把他们各自开一个单人群组即可, 用多个`PUSH_PLUS_USER`通知

这样做不到只推送他们自己账号呀，config那里都是一起发的

**Comment by qiangxinglin** [comment]
> > 推送加可以实现(pushplus), 把他们各自开一个单人群组即可, 用多个`PUSH_PLUS_USER`通知
> 
> 这样做不到只推送他们自己账号呀，config那里都是一起发的

如果是想一个容器内分别通知目前确实不行, 分开容器的话很容易做到分别通知

**Comment by chanho0** [comment]
> > > 推送加可以实现(pushplus), 把他们各自开一个单人群组即可, 用多个`PUSH_PLUS_USER`通知
> > 
> > 
> > 这样做不到只推送他们自己账号呀，config那里都是一起发的
> 
> 如果是想一个容器内分别通知目前确实不行, 分开容器的话很容易做到分别通知

原来你默认多容器，我代练4个号，多容器把我累死，算了，谢谢解答

**Comment by AboutCXJ** [comment]
> > > 推送加可以实现(pushplus), 把他们各自开一个单人群组即可, 用多个`PUSH_PLUS_USER`通知
> 
> > 
> 
> > 这样做不到只推送他们自己账号呀，config那里都是一起发的
> 
> 
> 
> 如果是想一个容器内分别通知目前确实不行, 分开容器的话很容易做到分别通知

多容器 微加云顶不住
