### ISSUE TITLE
年兽error

### ISSUE THREAD

**Issue by qiangxinglin** [LXK9301/jd_scripts#36]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [x] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：
node jd_nian.js出现如下报错
### (2) 详细日志
A：
```
TypeError: Cannot read property 'bizCode' of undefined
    at /scripts/jd_nian.js:342:27
    at got.post.then.message (/scripts/jd_nian.js:634:5694)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### (1) Node.js版本

A：
v14.15.4
### (2) npm版本

A：
6.14.10
### (3)npm install的日志

A：

**Comment by LXK9301** [comment]
这个出错忽略即可。暂不影响使用
