### ISSUE TITLE
能否增加企业微信应用通知

### ISSUE THREAD

**Issue by vay1314** [LXK9301/jd_scripts#37]
## 期望增加的功能

A：能否增加企业微信应用通知，企业微信应用通知推送也能推送到普通微信
需要corpid的值,corpsecret的值,touser的值,agentid,media_id的值
文档:https://work.weixin.qq.com/api/doc/90000/90135/90236

## 入口

A：

**Comment by sxx1314** [comment]
[早已支持](https://github.com/LXK9301/jd_scripts/blob/master/sendNotify.js)

**Comment by vay1314** [comment]
> [早已支持](https://github.com/LXK9301/jd_scripts/blob/master/sendNotify.js)

没看见变量写这个，以为不支持
