### ISSUE TITLE
征集京东APP的UserAgent

### ISSUE THREAD

**Issue by LXK9301** [LXK9301/jd_scripts#38]
征集一些京东APP的UserAgent放入到此文件，也可PR过来

https://github.com/LXK9301/jd_scripts/blob/master/USER_AGENTS.js

**Comment by xiaoyao0081** [comment]
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

**Comment by qxy0789** [comment]
问一下大佬，什么是UserAgent，怎么获取？

**Comment by LXK9301** [comment]
> 问一下大佬，什么是UserAgent，怎么获取？

这。。。抓包京东app即可看到

**Comment by mengdie101** [comment]
jdapp;android;9.3.6;9;D256434363461-6531383831656;network/wifi;model/MI 6;addressid/856540565;aid/f0ee06ebc7f6e98f;oaid/7fed3628fe652595;osVer/28;appBuild/86533;psn/V0yRdEdRydfYb9nackt2CQ==|3683;psq/0;adk/;ads/;pap/JA2015_311210|9.3.6|ANDROID 9;osv/9;pv/3513.0;jdv/0|kong|t_1000089893_|tuiguang|72e393e7b2474bc6a2369615f1b262e5|1610986845;ref/;partner/jingdong;apprpd/;eufv/1;Mozilla/5.0 (Linux; Android 9; MI 6 Build/PKQ1.190118.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 MQQBrowser/6.2 TBS/044942 Mobile Safari/537.36
这样可以吗

**Comment by 124754649** [comment]
jdapp;android;9.3.6;11;2353632303533303-4613731326261636;network/wifi;model/Redmi K30 5G;addressid/137593713;aid/25620530d171bbac;oaid/bfa9b0b7eca0475e;osVer/30;appBuild/86560;psn/oAPbHSW3fqrTmO6vGi1h73hJ0XCn9xEB|2846;psq/6;adk/;ads/;pap/JA2015_311210|9.3.6|ANDROID 11;osv/11;pv/2763.63;jdv/0|kong|t_1000089893_157_0_184__6fe1ce2ddf1f49a0|jingfen|249389d15ac843dbbbec52ce919891fb|1610851978;ref/com.jingdong.app.mall.home.JDHomeFragment;partner/xiaomi001;apprpd/Home_Main;eufv/1;jdSupportDarkMode/0;Mozilla/5.0 (Linux; Android 11; Redmi K30 5G Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.120 MQQBrowser/6.2 TBS/045511 Mobile Safari/537.36

刚新鲜热乎提出来的，不知道有没用！

**Comment by 25ma** [comment]
我的iphone 6s   os :11.4

User-Agent: jdpingou;iPhone;4.0.0;11.4;9ed0d69aaf190b5b4277868d2c0470fe1f787080;network/wifi;model/iPhone8,1;appBuild/100401;ADID/64199E21-4ECD-4217-BD79-0C4D82033FD8;supportApplePay/1;hasUPPay/0;pushNoticeIsOpen/1;hasOCPay/0;supportBestPay/0;session/73;pap/JA2019_3111789;brand/apple;supportJDSHWK/1;Mozilla/5.0 (iPhone; CPU iPhone OS 11_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15F79

**Comment by LXK9301** [comment]
> jdapp;android;9.3.6;9;D256434363461-6531383831656;network/wifi;model/MI 6;addressid/856540565;aid/f0ee06ebc7f6e98f;oaid/7fed3628fe652595;osVer/28;appBuild/86533;psn/V0yRdEdRydfYb9nackt2CQ==|3683;psq/0;adk/;ads/;pap/JA2015_311210|9.3.6|ANDROID 9;osv/9;pv/3513.0;jdv/0|kong|t_1000089893_|tuiguang|72e393e7b2474bc6a2369615f1b262e5|1610986845;ref/;partner/jingdong;apprpd/;eufv/1;Mozilla/5.0 (Linux; Android 9; MI 6 Build/PKQ1.190118.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 MQQBrowser/6.2 TBS/044942 Mobile Safari/537.36
> 这样可以吗

可以

**Comment by LXK9301** [comment]
> jdapp;android;9.3.6;11;2353632303533303-4613731326261636;network/wifi;model/Redmi K30 5G;addressid/137593713;aid/25620530d171bbac;oaid/bfa9b0b7eca0475e;osVer/30;appBuild/86560;psn/oAPbHSW3fqrTmO6vGi1h73hJ0XCn9xEB|2846;psq/6;adk/;ads/;pap/JA2015_311210|9.3.6|ANDROID 11;osv/11;pv/2763.63;jdv/0|kong|t_1000089893_157_0_184__6fe1ce2ddf1f49a0|jingfen|249389d15ac843dbbbec52ce919891fb|1610851978;ref/com.jingdong.app.mall.home.JDHomeFragment;partner/xiaomi001;apprpd/Home_Main;eufv/1;jdSupportDarkMode/0;Mozilla/5.0 (Linux; Android 11; Redmi K30 5G Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.120 MQQBrowser/6.2 TBS/045511 Mobile Safari/537.36
> 
> 刚新鲜热乎提出来的，不知道有没用！

可以

**Comment by LXK9301** [comment]
> 我的iphone 6s os :11.4
> 
> User-Agent: jdpingou;iPhone;4.0.0;11.4;9ed0d69aaf190b5b4277868d2c0470fe1f787080;network/wifi;model/iPhone8,1;appBuild/100401;ADID/64199E21-4ECD-4217-BD79-0C4D82033FD8;supportApplePay/1;hasUPPay/0;pushNoticeIsOpen/1;hasOCPay/0;supportBestPay/0;session/73;pap/JA2019_3111789;brand/apple;supportJDSHWK/1;Mozilla/5.0 (iPhone; CPU iPhone OS 11_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15F79

这个不行， 不是京东app的， 你这是京喜

**Comment by EricChin2012** [comment]
User-Agent: jdapp;iPhone;9.2.4;14.1;b9d474077232e439a03d610bc11e3861a0296b67;network/wifi;supportApplePay/0;hasUPPay/0;hasOCPay/0;model/iPhone11,8;addressid/13377806;supportBestPay/0;appBuild/167432;pushNoticeIsOpen/0;jdSupportDarkMode/0;pv/259.20;apprpd/Home_Main;ref/JDMainPageViewController;psq/17;ads/;psn/b9d474077232e439a03d610bc11e3861a0296b67|675;jdv/0|kong|t_1000089893_|tuiguang|c37639dcb10b43c0a4ceb54b19be50cf|1610978908;adk/;app_device/IOS;pap/JA2015_311210|9.2.4|IOS 14.1;Mozilla/5.0 (iPhone; CPU iPhone OS 14_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148;supportJDSHWK/1

**Comment by chenkid999** [comment]
jdapp;android;9.3.6;10;8363037353830343533303236333-73D2438323361603735616833316;network/UNKNOWN;model/MI 8;addressid/2532472939;aid/b5de2a5d9ce280f6;oaid/867c11ae16e94d11;osVer/29;appBuild/86560;partner/xiaomi001;eufv/1;jdSupportDarkMode/0;Mozilla/5.0 (Linux; Android 10; MI 8 Build/QKQ1.190828.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.120 MQQBrowser/6.2 TBS/045227 Mobile Safari/537.36

**Comment by chenkid999** [comment]
jdapp;android;9.3.6;11;2643139303035683-6326533623539333;network/UNKNOWN;model/Redmi K20 Pro Premium Edition;addressid/0;aid/b41900e86b5c2593;oaid/a1ae016fae05d3c8;osVer/30;appBuild/86560;partner/xiaomi001;eufv/1;jdSupportDarkMode/0;Mozilla/5.0 (Linux; Android 11; Redmi K20 Pro Premium Edition Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.120 MQQBrowser/6.2 TBS/045513 Mobile Safari/537.36

**Comment by Smart-Pikachu** [comment]
只有下面这一串，为甚恶魔你们的都好长，而我抓包出来只有这么一点点····

JD4iPhone/9.3.5 CFNetwork/1209 Darwin/20.2.0

**Comment by conan257** [comment]
> 只有下面这一串，为甚恶魔你们的都好长，而我抓包出来只有这么一点点····
> 
> JD4iPhone/9.3.5 CFNetwork/1209 Darwin/20.2.0

你的抓包工具是不是没有安装证书

**Comment by XiaoDonglu** [comment]
jdapp;iPhone;9.3.5;14.3;85ce08e05756b547e15f0b637cc99addd96b3345;network/4g;supportApplePay/0;hasUPPay/0;hasOCPay/0;model/iPhone12,1;addressid/138116050;supportBestPay/0;appBuild/167515;jdSupportDarkMode/0;pv/524.2;apprpd/Home_Main;ref/JDMainPageViewController;psq/1;ads/;psn/85ce08e05756b547e15f0b637cc99addd96b3345|1591;jdv/0|kong|t_1000170136|tuiguang|notset|1609480641159|1609480641;adk/;app_device/IOS;pap/JA2015_311210|9.3.5|IOS 14.3;Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148;supportJDSHWK/1

**Comment by gjmdx** [comment]
jdapp;iPhone;9.3.5;14.3;244bd50c51f0b198dd8733afe89cdec4b09df713;network/wifi;JDEbook/openapp.jdreader;supportApplePay/0;hasUPPay/0;hasOCPay/0;model/iPhone8,2;addressid/0;supportBestPay/0;appBuild/167515;jdSupportDarkMode/0;pv/2.2;apprpd/Home_Main;ref/JDMainPageViewController;psq/1;ads/;psn/244bd50c51f0b198dd8733afe89cdec4b09df713|2;jdv/0|;adk/;app_device/IOS;pap/JA2015_311210|9.3.5|IOS 14.3;Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148;supportJDSHWK/1

**Comment by liwenjie119** [comment]
> jdapp;android;9.3.6;11;2643139303035683-6326533623539333;network/UNKNOWN;model/Redmi K20 Pro Premium Edition;addressid/0;aid/b41900e86b5c2593;oaid/a1ae016fae05d3c8;osVer/30;appBuild/86560;partner/xiaomi001;eufv/1;jdSupportDarkMode/0;Mozilla/5.0 (Linux; Android 11; Redmi K20 Pro Premium Edition Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.120 MQQBrowser/6.2 TBS/045513 Mobile Safari/537.36

用啥抓的包啊，我住不到，提示目标使用固定的证书

**Comment by anyhui** [comment]
米10 Mozilla/5.0 (Linux; U; Android 11; zh-cn; Mi 10 Build/RKQ1.200826.002) AppleWebKit/533.1 (KHTML, like Gecko) Mobile Safari/533.1

**Comment by nie115** [comment]
jdapp;android;9.3.4;10;9356665333362626-4603362346333356;network/UNKNOWN;model/Redmi K20 Pro Premium Edition;addressid/137826363;aid/9ef53cbbd0c2d33e;oaid/ec7c5827275510c6;osVer/29;appBuild/86388;psn/DlHZjadWfe77DEYHrpjFjvKonV0SSFdy|921;psq/2;adk/;ads/;pap/JA2015_311210|9.3.4|ANDROID 10;osv/10;pv/793.2;jdv/0|kong|t_1000089893_|tuiguang|7459d8cb7c8f4f9f8e6e87751f61bd18|1611236364;ref/com.jd.lib.personal.view.fragment.JDPersonalFragment;partner/xiaomi001;apprpd/MyJD_Main;eufv/1;jdSupportDarkMode/0;Mozilla/5.0 (Linux; Android 10; Redmi K20 Pro Premium Edition Build/QKQ1.190825.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.120 MQQBrowser/6.2 TBS/045227 Mobile Safari/537.36

**Comment by nie115** [comment]
Dalvik/2.1.0 (Linux; U; Android 10; Redmi K20 Pro Premium Edition MIUI/V12.0.5.0.QFKCNXM)

**Comment by jiebozhang** [comment]
jdapp;android;9.2.2;8.1.0;869071037529592-9487e01e7f2d;network/wifi;model/MI 8;addressid/2769817385;aid/f4ed3e79ab29f481;oaid/;osVer/27;appBuild/85371;partner/xiaomi001;jdSupportDarkMode/0;Mozilla/5.0 (Linux; Android 8.1.0; MI 8 Build/OPM1.171019.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 MQQBrowser/6.2 TBS/045131 Mobile Safari/537.36

**Comment by lvaneasylam** [comment]
iphone :
User-Agent: jdapp;iPhone;9.3.4;14.2;be1acbcd17e4c25aeb5bc17c7567a8fa44ce9cab;network/wifi;ADID/04974BAF-2BED-45AC-A0AE-2242820A3C4F;supportApplePay/0;hasUPPay/0;hasOCPay/0;model/iPhone13,4;addressid/1083782522;supportBestPay/0;appBuild/167502;jdSupportDarkMode/0;pv/1548.4;apprpd/Home_Main;ref/JDMainPageViewController;psq/1;ads/;psn/be1acbcd17e4c25aeb5bc17c7567a8fa44ce9cab|2101;jdv/0|kong|t_1000170135|tuiguang|notset|1611232250866|1611232250;adk/;app_device/IOS;pap/JA2015_311210|9.3.4|IOS 14.2;Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148;supportJDSHWK/1

**Comment by lrxwwm** [comment]
jdapp;iPhone;9.3.5;14.3;f43410af69a81012383ca839707069b2a4c68e27;network/wifi;supportApplePay/0;hasUPPay/0;hasOCPay/0;model/iPhone11,8;addressid/3064531114;supportBestPay/0;appBuild/167515;jdSupportDarkMode/0;pv/481.19;apprpd/Home_Main;ref/JDMainPageViewController;psq/1;ads/;psn/f43410af69a81012383ca839707069b2a4c68e27|1274;jdv/0|kong|t_1000170136|tuiguang|notset|1611275169877|1611280752;adk/;app_device/IOS;pap/JA2015_311210|9.3.5|IOS 14.3;Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148;supportJDSHWK/1

**Comment by Daniel-sweet-Q** [comment]
jdapp;iPhone;9.3.5;14.2;075879f1ae1f0fede61c030eb6b3e7b1b0ce9ae2;network/wifi;ADID/88BBE341-AE7D-4789-B7D9-B5EBBFF413A5;supportApplePay/0;hasUPPay/0;hasOCPay/0;model/iPhone10,3;addressid/138021169;supportBestPay/0;appBuild/167515;jdSupportDarkMode/0;pv/980.15;apprpd/MyCalendar_ActivityCalendar;ref/;psq/4;ads/;psn/075879f1ae1f0fede61c030eb6b3e7b1b0ce9ae2|3781;jdv/0|direct|-|none|-|1611189859248|1611189890;adk/;app_device/IOS;pap/JA2015_311210|9.3.5|IOS 14.2;Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148;supportJDSHWK/1

**Comment by hardyio** [comment]
Dalvik/2.1.0 (Linux; U; Android 8.0.0; ZTE A2017 Build/OPR1.170623.032)

**Comment by crazylcc** [comment]
JD4iPhone/9.3.5 CFNetwork/1206 Darwin/20.1.0

**Comment by Smart-Pikachu** [comment]
> > 只有下面这一串，为甚恶魔你们的都好长，而我抓包出来只有这么一点点····
> > JD4iPhone/9.3.5 CFNetwork/1209 Darwin/20.2.0
> 
> 你的抓包工具是不是没有安装证书

安装证书了，我看好像有其他人也是跟我一样的···

**Comment by loyio** [comment]
> 只有下面这一串，为甚恶魔你们的都好长，而我抓包出来只有这么一点点····
> 
> JD4iPhone/9.3.5 CFNetwork/1209 Darwin/20.2.0

我用Surge抓的包,也只有这么长，MitM设置好了，你也是Surge吗
> JD4iPhone/167515 (iPhone; iOS 14.3; Scale/3.00)

**Comment by DorkyRabbit** [comment]
提供个安卓华为的
jdapp;android;9.3.6;10;8363434323030343235333838383-93D2134346136393268356361326;network/wifi;model/LYA-AL00;addressid/514336649;aid/4566072c8d9c08ac;oaid/00000000-0000-0000-0000-000000000000;osVer/29;appBuild/86560;partner/huawei;eufv/1;jdSupportDarkMode/0;Mozilla/5.0 (Linux; Android 10; LYA-AL00 Build/HUAWEILYA-AL00L; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.120 MQQBrowser/6.2 TBS/045230 Mobile Safari/537.36

**Comment by laststory117** [comment]
"jdapp;iPhone;9.3.5;14.0.1;f467d6c04cd809e79dc000c574f8f79f00948dbc;network/wifi;ADID/60D6729F-9462-416A-84BA-087DE63342EA;supportApplePay/0;hasUPPay/0;hasOCPay/0;model/iPhone10,2;addressid/138086175;supportBestPay/0;appBuild/167515;jdSupportDarkMode/0;pv/1122.25;apprpd/Babel_Native;ref/https%3A%2F%2Fwbbny.m.jd.com%2FbabelDiy%2FZeus%2F2cKMj86srRdhgWcKonfExzK4ZMBy%2Findex.html%3FbabelChannel%3Djx%26lng%3D118.734885%26lat%3D31.980189%26sid%3D5ac4902e0d1350a80f8127f88cc27c3w%26un_area%3D12_904_3379_62183%23%2Fhome;psq/0;ads/;psn/f467d6c04cd809e79dc000c574f8f79f00948dbc|3145;jdv/0|kong|t_1001597287_27078064|jingfen|ba710561492a446da2815e561082c75b|1611304510000|1611367639|1611367690;adk/;app_device/IOS;pap/JA2015_311210|9.3.5|IOS 14.0.1;Mozilla/5.0 (iPhone; CPU iPhone OS 14_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148;supportJDSHWK/1"

**Comment by zhongyouhuiwu** [comment]
htc u11:
jdapp;android;9.3.6;8.0.0;3353936343830383030333835333-53D2430343563363237316933336;network/wifi;model/HTC U-3w;addressid/1077019363;aid/c62026bb64774879;oaid/;osVer/26;appBuild/86560;partner/jingdong;eufv/1;Mozilla/5.0 (Linux; Android 8.0.0; HTC U-3w Build/OPR6.170623.013; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 MQQBrowser/6.2 TBS/044942 Mobile Safari/537.36

**Comment by zhongyouhuiwu** [comment]
iphone xr:
jdapp;iPhone;9.3.7;14.3;838e40e70281c7e7c03f32f3772f53e4118b2aee;network/wifi;supportApplePay/0;hasUPPay/0;hasOCPay/0;model/iPhone11,8;addressid/138238913;supportBestPay/0;appBuild/167536;jdSupportDarkMode/0;pv/7532.2;apprpd/Home_Main;ref/JDMainPageViewController;psq/1;ads/;psn/838e40e70281c7e7c03f32f3772f53e4118b2aee|12414;jdv/0|kong|t_1000089893_157_0_184__8f5df3664254689b|tuiguang|103a4567f4b34409926ba37dbbe001bb|1611484786;adk/;app_device/IOS;pap/JA2015_311210|9.3.7|IOS 14.3;Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148;supportJDSHWK/1

**Comment by singyueyang** [comment]
魅族的：    jdapp;android;8.5.2;8.1.0;865664032788249-90f05250a015;network/wifi;model/16 X;addressid/137581227;aid/99e3cd08cf5f0a2c;oaid/;osVer/27;appBuild/71869;partner/meizu;Mozilla/5.0 (Linux; Android 8.1.0; 16 X Build/OPM1.171019.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 MQQBrowser/6.2 TBS/044942 Mobile Safari/537.36

**Comment by jyxq404** [comment]
jdapp;android;9.1.0;9;864360034117260-18d276c8a45f;network/wifi;model/MHA-AL00;addressid/2013852661;aid/6edf28a51a564bc7;oaid/7efede7f-7ffb-839d-d58f-7f7b7ff9c1ee;osVer/28;appBuild/83789;partner/jingdong;Mozilla/5.0 (Linux; Android 9; MHA-AL00 Build/HUAWEIMHA-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 MQQBrowser/6.2 TBS/044942 Mobile Safari/537.36

**Comment by LXK9301** [comment]
已收录

**Comment by jerrykkkkk** [comment]
Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/8.0.1(0x18000122) NetType/WIFI Language/zh_CN
