### ISSUE TITLE
京喜工厂每日任务和收取电力出错

### ISSUE THREAD

**Issue by Misaka09982** [LXK9301/jd_scripts#4]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否仔细阅读了教程
- [x ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [x ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：我有五个账号中有两个账号是没办法做每日任务和收取电力，自己手动正常做，麻烦哪个大佬解决下，还是说我的账号被限制了

### (2) 详细日志
A：nextCollectDoubleFlag::0
nextCollectDoubleType::0

下次集满收取不可双倍电力
发电机：当前 359.1 电力，最大值 360 电力
收取电力失败:活动火爆，请稍后再试~

去做任务：[限时]瓜分1.5万电仅需5人
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取[限时]瓜分1.5万电仅需5人任务奖励失败，任务已领奖
去做任务：[限时]瓜分1.5万电仅需5人
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取[限时]瓜分1.5万电仅需5人任务奖励失败，任务已领奖
任务：每日开工打卡可完成
领取每日开工打卡任务奖励成功，收获：100电力
去做任务：上集市做调研30s
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取上集市做调研30s任务奖励失败，任务已领奖
去做任务：上集市做调研30s
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取上集市做调研30s任务奖励失败，任务已领奖
去做任务：去集市发现5件好物
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集市发现5件好物任务奖励失败，任务已领奖
去做任务：去集市发现5件好物
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集市发现5件好物任务奖励失败，任务已领奖
去做任务：去集市发现5件好物
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集市发现5件好物任务奖励失败，任务已领奖
去做任务：去集市发现5件好物
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集市发现5件好物任务奖励失败，任务已领奖
去做任务：去集市发现5件好物
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集市发现5件好物任务奖励失败，任务已领奖
去做任务：去集市发现5件好物
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集市发现5件好物任务奖励失败，任务已领奖
任务：登录APP领取奖励可完成
领取登录APP领取奖励任务奖励成功，收获：2500电力
去做任务：开宝箱找安全帽
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取开宝箱找安全帽任务奖励失败，任务已领奖
去做任务：开宝箱找安全帽
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取开宝箱找安全帽任务奖励失败，任务已领奖
去做任务：去签到，可领现金提现
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去签到，可领现金提现任务奖励失败，任务已领奖
去做任务：去签到，可领现金提现
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去签到，可领现金提现任务奖励失败，任务已领奖
去做任务：去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！任务奖励失败，任务已领奖
去做任务：去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！任务奖励失败，任务已领奖
去做任务：去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！任务奖励失败，任务已领奖
去做任务：去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！任务奖励失败，任务已领奖
去做任务：上岛兑0元好物,逛农场免费领水果,出海寻宝领100元红包
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取上岛兑0元好物,逛农场免费领水果,出海寻宝领100元红包任务奖励失败，任务已领奖
去做任务：上岛兑0元好物,逛农场免费领水果,出海寻宝领100元红包
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取上岛兑0元好物,逛农场免费领水果,出海寻宝领100元红包任务奖励失败，任务已领奖
去做任务：上岛兑0元好物,逛农场免费领水果,出海寻宝领100元红包
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取上岛兑0元好物,逛农场免费领水果,出海寻宝领100元红包任务奖励失败，任务已领奖
去做任务：上岛兑0元好物,逛农场免费领水果,出海寻宝领100元红包
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取上岛兑0元好物,逛农场免费领水果,出海寻宝领100元红包任务奖励失败，任务已领奖
完成任务：共领取2600电力
成功投入电力3700电力
打工电力：收取失败，活动火爆，请稍后再试~
收自己地下零件失败：好可惜,没中奖哦~,直接跳出
今日收取零件已达上限，偷好友零件也达到上限，故跳出

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by me56** [comment]
同样的问题，出现很长时间了。望大佬看看咋回事

**Comment by tianya908** [comment]
同样的问题，报这个错误DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}。望大佬看看咋回事

**Comment by sltalex** [comment]
这是账号被风控了，互助没问题，做任务和收电只能手工了。

**Comment by bontheway** [comment]
> 这是账号被风控了，互助没问题，做任务和收电只能手工了。

有什么解决办法么

**Comment by xiaoyao0081** [comment]
测试了一下，不是风控，而是必须从京喜APP做任务才能完成，jingdongAPP无法完成任务，期待大佬解决一下

**Comment by thincen** [comment]
还以为是User-Agent的原因

**Comment by afracn** [comment]
同样的问题  几个号一起跑，就只有一个号会这样

**Comment by yulinsoft** [comment]
我也有这个问题，三个号中有一个是这个情况，只能在京东app中手动领取。

**Comment by ekonoob** [comment]
一样的，请问有解决方法吗？

**Comment by LXK9301** [comment]
没得解。我自己所有账号目前正常。

等你账号正常吧

**Comment by Oscar1011** [comment]
app里可以手动做任务，抓了包感觉是ua问题。

**Comment by LXK9301** [comment]
@Oscar1011 那你把脚本下载到pc 本地。然后改成你自己的ua 试试看？

**Comment by Oscar1011** [comment]
试了好像不行。。。。蛋疼

**Comment by thincen** [comment]
> 试了好像不行。。。。蛋疼

就是,我也试了,还是一样

**Comment by sxx1314** [comment]
````
领取去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！,去京东看年货清单任务奖励成功，收获：100电力
去做任务：去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！,去京东看年货清单
做任务完成！
领取去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！,去京东看年货清单任务奖励成功，收获：100电力
去做任务：去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！,去京东看年货清单
DoTask异常：{"data":{"awardStatus":1,"completedTimes":4,"dateTypeExtra":"20210123","updateTime":1611352928,"userStatusConfigExtra":""},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":1009}
````

还是蛮奇葩的，有几个任务做的完，有几个就做不了。
