### ISSUE TITLE
酷推推送异常: undefined

### ISSUE THREAD

**Issue by alex300414** [LXK9301/jd_scripts#40]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [x] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：BARK，SERVER酱推送正常，酷推推送异常: undefined

### (2) 详细日志
A：
酷推推送异常: undefined
Bark APP发送通知消息成功

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by LXK9301** [comment]
推送那边的问题估计。之前正常如果现在不行。可能服务器挂了 或者机器人被封了

**Comment by alex300414** [comment]
秒回！单独测试酷推正常，不用也没事，只是发现酷推失败，没有大碍。

**Comment by Hthing** [comment]
> 推送那边的问题估计。之前正常如果现在不行。可能服务器挂了 或者机器人被封了

我昨天才开始用这个脚本，遇到同样问题，发现是被和谐了。敏感词还有不少 ，只能不用这个了
另外我看代码里用的是msg， 而响应是message。 所以报了未定义
{"code":503,"message":"检测到敏感词","data":"京豆"}

**Comment by alex300414** [comment]
> > 推送那边的问题估计。之前正常如果现在不行。可能服务器挂了 或者机器人被封了
> 
> 我昨天才开始用这个脚本，遇到同样问题，发现是被和谐了。敏感词还有不少 ，只能不用这个了
> 另外我看代码里用的是msg， 而响应是message。 所以报了未定义
> {"code":503,"message":"检测到敏感词","data":"京豆"}

我也是不用他了，但是搞不明白酷推还搞这个关键字屏蔽干什么……
