### ISSUE TITLE
东东工厂报错❌

### ISSUE THREAD

**Issue by Volatile0** [LXK9301/jd_scripts#45]
2021-01-18T06:03:13.531Z cba3d9c9-5e6b-4b0d-b5d7-e6b75f4bd393
❗️东东工厂, 错误!
TypeError: Cannot read property '0' of undefined
    at eval (eval at <anonymous> (/var/user/index.js:20:9), <anonymous>:220:55)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by Volatile0** [comment]
腾讯云函数部署的

**Comment by hejun041** [comment]
`{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"SyntaxError: Unexpected token '\u003c'\n    at Request._callback (/var/user/index.js:15:23)\n    at Request.self.callback (/var/user/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:311:20)\n    at Request.\u003canonymous\u003e (/var/user/node_modules/request/request.js:1154:10)\n    at Request.emit (events.js:311:20)\n    at IncomingMessage.\u003canonymous\u003e (/var/user/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (events.js:417:28)\n    at IncomingMessage.emit (events.js:323:22)\n    at endReadableNT (_stream_readable.js:1204:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","statusCode":430}`
同
