### ISSUE TITLE
运行任意脚本都是相同报错。TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by luovivi** [LXK9301/jd_scripts#5]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [x] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：运行任意脚本都是相同报错。TypeError: Cannot read property 'split' of undefined

### (2) 详细日志
A：START RequestId: 322c4d67-a115-48ea-9d2b-1bf16e95e399

Event RequestId: 322c4d67-a115-48ea-9d2b-1bf16e95e399

2021-01-16T12:27:24.522Z  322c4d67-a115-48ea-9d2b-1bf16e95e399  TypeError: Cannot read property 'split' of undefined

    at Runtime.exports.main_handler [as handler] (/var/user/index.js:6:38)

    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:215:23)

### (1) Node.js版本

A：v14.15.4

### (2) npm版本

A：6.14.10

### (3)npm install的日志

A：audited 206 packages in 2.183s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by wudongdefeng** [comment]
你这个是网络不好，运行位置换成本地版就好了

**Comment by LXK9301** [comment]
你这个问题都是老问题。好好看下教程吧

触发器那边附加信息是一个一个填写脚本名称

**Comment by koo9966** [comment]
请问一下，cookies是填在github里面，还是腾讯云的哪个文件里

**Comment by luovivi** [comment]
> 你这个问题都是老问题。好好看下教程吧
> 
> 触发器那边附加信息是一个一个填写脚本名称

它自动部署完就生成了10个触发器，昨晚自动执行成功了，我之前是手动点测试全都是那个报错。请问大佬如何手动测试，能知道是否部署成功呢？

**Comment by luovivi** [comment]
> 请问一下，cookies是填在github里面，还是腾讯云的哪个文件里

**Comment by koo9966** [comment]
请问一下，cookies是填在github里面，还是腾讯云的哪个文件里

**Comment by koo9966** [comment]
我在github填 了,cookies,但是部署的时间,环境变量里面没有

**Comment by koo9966** [comment]
云部署里面的助力码怎么填 啊

**Comment by luovivi** [comment]
> 请问一下，cookies是填在github里面，还是腾讯云的哪个文件里

腾讯云jdcookies

**Comment by koo9966** [comment]
助力码填在哪里,cookice已经填好啊,

**Comment by koo9966** [comment]
我把助力码填 在serverless.yml里面了,但是,显示没有互助码

**Comment by koo9966** [comment]
@luovivi 求指教谢谢

**Comment by tanranran** [comment]
@koo9966 能分享一下您的serverless.yml 想在这里面配置cookice
