### ISSUE TITLE
jd_bean_sign.js 下载 JD_DailyBonus.js 不会读取 env 设置的 proxy 吗？

### ISSUE THREAD

**Issue by LisonFan** [LXK9301/jd_scripts#52]
```
Jan 16 18:00:17 {"name":"RequestError","code":"ECONNREFUSED","timings":{"start":1610791217453,"socket":1610791217454,"lookup":1610791217459,"error":1610791217494,"phases":{"wait":1,"dns":5,"total":41}}}
Jan 16 18:00:17 检测到您不能访问外网,将使用CDN下载JD_DailyBonus.js文件
```

docker 部署，在环境变量里设置了 http/https/socks5 的 proxy 地址，但是我看 `jd_bean_sign.js` 去下载的时候并没有获取代理地址去下载

**Comment by LXK9301** [comment]
> ```
> Jan 16 18:00:17 {"name":"RequestError","code":"ECONNREFUSED","timings":{"start":1610791217453,"socket":1610791217454,"lookup":1610791217459,"error":1610791217494,"phases":{"wait":1,"dns":5,"total":41}}}
> Jan 16 18:00:17 检测到您不能访问外网,将使用CDN下载JD_DailyBonus.js文件
> ```
> 
> 
> docker 部署，在环境变量里设置了 http/https/socks5 的 proxy 地址，但是我看 `jd_bean_sign.js` 去下载的时候并没有获取代理地址去下载

嗯。目前是没有

**Comment by LXK9301** [comment]
@LisonFan 已支持 更新后， 测试一下

**Comment by LisonFan** [comment]
> @LisonFan 已支持 更新后， 测试一下

好的，我看了一下，脚本读的是`TG_PROXY_PORT` 和 `TG_PROXY_HOST`
我这边是设置的 `http_proxy https_proxy all_proxy`

**Comment by LXK9301** [comment]
> > @LisonFan 已支持 更新后， 测试一下
> 
> 好的，我看了一下，脚本读的是`TG_PROXY_PORT` 和 `TG_PROXY_HOST`
> 我这边是设置的 `http_proxy https_proxy all_proxy`
> 是按照脚本这样来呢，还是换成通用的做法？

那就是你的事情了， 我是按 环境变量集合来的。因为发送通知的tg机器人，也是按这个环境变量来的

**Comment by LXK9301** [comment]
已有的环境变量 不在修改，不然影响很大

**Comment by LisonFan** [comment]
@LXK9301 好的，按大佬的来

**Comment by LisonFan** [comment]
> > > @LisonFan 已支持 更新后， 测试一下
> > 
> > 
> > 好的，我看了一下，脚本读的是`TG_PROXY_PORT` 和 `TG_PROXY_HOST`
> > 我这边是设置的 `http_proxy https_proxy all_proxy`
> > 是按照脚本这样来呢，还是换成通用的做法？
> 
> 已有的环境变量 不在修改，不然影响很大
> 
> 其实功能是一样，但是我不想再新增别的环境变量了

ok 了，不会提示无法访问外网了
