### ISSUE TITLE
希望添加一个任务 就是删除 关注 以及 收藏

### ISSUE THREAD

**Issue by xiaotianwl** [LXK9301/jd_scripts#57]
希望添加一个任务 就是删除 关注 以及 收藏
挂机几天下来 发现关注商家已经快两百多家了！

**Comment by Elletear** [comment]
这个就是：[jd_unsubscribe.js](https://github.com/LXK9301/jd_scripts/blob/master/jd_unsubscribe.js)😂

**Comment by Michaol** [comment]
难道你从来不看readme？
