### ISSUE TITLE
 “店铺寻宝签到领爆竹” 任务没有做，每天11500个爆竹，盼加入

### ISSUE THREAD

**Issue by servicehost** [LXK9301/jd_scripts#58]
设备：x86软路由
系统：OpenWrt
执行方式：本地执行

【问题二】

活动页面拉到最下方，会有 “店铺寻宝签到领爆竹” 的任务，共计115个店铺，每个店铺签到都能得到100个爆竹。

该任务不属于集爆竹任务列表里的项目，需要拉到活动页面最下方，共有115个店铺，每个店铺进入后“点我领爆竹”都可以领到100爆竹，每天可以得到11500个爆竹。靠人工手点实在是累，盼大佬加入。

-----------------------------------------------------

【问题一】已解决

❗️京东炸年兽🧨, 错误!
TypeError: Cannot read property 'taskVos' of undefined
    at /scripts/jd_nian.js:568:46
    at got.post.then.message (/scripts/jd_nian.js:955:5694)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by fengmikaelson** [comment]
加入品牌会员的好像也没法做吧？

**Comment by servicehost** [comment]
> 
> 
> 加入品牌会员的好像也没法做吧？

加入会员是需要手机短信验证码的，自己手动操作。

**Comment by fengmikaelson** [comment]
> > 加入品牌会员的好像也没法做吧？
> 
> 加入会员是需要手机短信验证码的，自己手动操作。

另外问下，你的互助码都能正常生成吗？不知道为什么，我看sharecode里的互助码，少了一些活动。比如京东赚赚。。。

**Comment by LXK9301** [comment]
@fengmikaelson 目前助力活动本来就下线了。

还有就是如果今天被满了上限 就不会显示

**Comment by fengmikaelson** [comment]
> @fengmikaelson 目前助力活动本来就下线了。
> 
> 还有就是如果今天被满了上限 就不会显示

原来如此，多谢多谢。疑惑消除了。

**Comment by l18764** [comment]
> @fengmikaelson 目前助力活动本来就下线了。
> 
> 还有就是如果今天被满了上限 就不会显示

当前爆竹45860�，下一关需要327000�
可收取的爆竹大于0，去收取爆竹
收取成功，获得247爆竹�
当前已开启的地图：小镇车站
去做OLAY店铺任务

❗️京东炸年兽�, 错误!
TypeError: Cannot read property 'taskVos' of undefined
    at /storage/emulated/0/jd/scripts/jd_nian.js:566:46
    at got.post.then.message (/storage/emulated/0/jd/scripts/jd_nian.js:953:5694)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
去做宝洁店铺任务

❗️京东炸年兽�, 错误!
TypeError: Cannot read property 'taskVos' of undefined
    at /storage/emulated/0/jd/scripts/jd_nian.js:566:46
    at got.post.then.message (/storage/emulated/0/jd/scripts/jd_nian.js:953:5694)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
去做蒙牛店铺任务
设备：安卓
软件：termux
提示您提供了8个账号的京东炸年兽�助力码
但是执行只有一个账号运行，但是也运行失败，其他7个账号不运行，没有黑号

**Comment by MisterGlasses** [comment]
我也遇到了这个问题 第一个账号一出错误就退出了 导致别的号没有执行脚本

**Comment by LXK9301** [comment]
更新脚本试试看。或者使用自定义ua。自己提供一个京东app的ua

**Comment by Gino-Wong** [comment]
更新了脚本以后就成功运行了一次，第二次就出现了TypeError: Cannot read property 'taskVos' of undefined的错误

**Comment by MisterGlasses** [comment]
自定义ua了 还是不行

**Comment by LXK9301** [comment]
需要京东app的ua。 不是浏览器的

**Comment by lmchow** [comment]
什么是app的ua?

**Comment by Mark-1215** [comment]
> 需要京东app的ua。 不是浏览器的

同样的问题，已设置自己手机的UA，已解决，感谢

**Comment by servicehost** [comment]
> 
> 
> > 需要京东app的ua。 不是浏览器的
> 
> 同样的问题，已设置自己手机的UA，已解决，感谢

请问下你是如何获取自己京东APP的内置UA的？有什么简单的办法吗？
我尝试用APP扫获取UA内容的二维码，但京东APP会提示外部浏览器打开，而不是在他内部打开。

**Comment by hengwuming** [comment]
> 需要京东app的ua。 不是浏览器的

大佬，在哪填写我自己的UA呢

**Comment by servicehost** [comment]
> 
> 
> 需要京东app的ua。 不是浏览器的

OK，改用了自己的android手机UA后任务执行不会再出现taskVos的错误了，应该是iOS和android系统的任务内容不太一样造成的，而之前随机UA中只有1个android手机的UA，大概率会碰到iOS的UA，导致出错。

现在就剩【问题二】暂未解决了，该任务不属于集爆竹任务列表里的项目，需要拉到活动页面最下方，共有115个店铺，每个店铺进入后“点我领爆竹”都可以领到100爆竹，每天可以得到11500个爆竹。靠人工手点实在是累，盼大佬加入。

**Comment by LXK9301** [comment]
> > 需要京东app的ua。 不是浏览器的
> 
> OK，改用了自己的android手机UA后任务执行不会再出现taskVos的错误了，应该是iOS和android系统的任务内容不太一样造成的，而之前随机UA中只有1个android手机的UA，大概率会碰到iOS的UA，导致出错。
> 
> 现在就剩【问题二】暂未解决了，该任务不属于集爆竹任务列表里的项目，需要拉到活动页面最下方，共有115个店铺，每个店铺进入后“点我领爆竹”都可以领到100爆竹，每天可以得到11500个爆竹。靠人工手点实在是累，盼大佬加入。

https://github.com/LXK9301/jd_scripts/pull/90

已有

**Comment by servicehost** [comment]
> 
> 
> > > 需要京东app的ua。 不是浏览器的
> > 
> > 
> > OK，改用了自己的android手机UA后任务执行不会再出现taskVos的错误了，应该是iOS和android系统的任务内容不太一样造成的，而之前随机UA中只有1个android手机的UA，大概率会碰到iOS的UA，导致出错。
> > 现在就剩【问题二】暂未解决了，该任务不属于集爆竹任务列表里的项目，需要拉到活动页面最下方，共有115个店铺，每个店铺进入后“点我领爆竹”都可以领到100爆竹，每天可以得到11500个爆竹。靠人工手点实在是累，盼大佬加入。
> 
> #90
> 
> 已有

实测最新的脚本依然是没有些功能的，我已经多次执行了脚本，下面的115个店铺依然没有做“点我领爆竹”的任务。

你可以自己进入APP看看“点我领爆竹”任务有没有做。

请注意：该任务不属于 “集爆竹任务列表里” 的可视项目，需要一直拉到活动页面最下方，一大堆小方块的店铺即是。（上方也有些长方形的小方块店铺，但那些与此任务无关），我估计是你把这个与上面的任务弄混了。

**Comment by servicehost** [comment]
> 已有

[![s2s3fe.jpg](https://s3.ax1x.com/2021/01/19/s2s3fe.jpg)](https://imgchr.com/i/s2s3fe)
[![s2sGSH.jpg](https://s3.ax1x.com/2021/01/19/s2sGSH.jpg)](https://imgchr.com/i/s2sGSH)
[![s2s1YD.jpg](https://s3.ax1x.com/2021/01/19/s2s1YD.jpg)](https://imgchr.com/i/s2s1YD)

**Comment by sofs2005** [comment]
确实没有那一百多个店的领爆竹

**Comment by google-mirror** [comment]
+1

**Comment by MisterGlasses** [comment]
新出的签到脚本应该可以

**Comment by shylocks** [comment]
fix in ada89c9f26631c12f86afef273dfb90d3ba310aa
