### ISSUE TITLE
今天重新拉取活动后，新增的炸年兽脚本不运行，是定时器没到吗...

### ISSUE THREAD

**Issue by Gino-Wong** [LXK9301/jd_scripts#61]
早晨就自动拉取了活动，但是新增的jd_nian.sh一直都没有运行，我看定时器里写的是0 8,9,10 * * * bash jd jd_nian，这是什么意思呢

**Comment by l18764** [comment]
0代表是0分  8.9.10是钟，三个时间点都执行一次任务。那三个时间点？看我发的

**Comment by l18764** [comment]
8.9.10代表时，习惯说方言了

**Comment by Gino-Wong** [comment]
> 8.9.10代表时，习惯说方言了

哈哈哈 懂啦 谢谢
