### ISSUE TITLE
请问joy挂机（docker）能否关闭

### ISSUE THREAD

**Issue by hclasmn** [LXK9301/jd_scripts#63]
请问joy挂机（docker）能否关闭

**Comment by iouAkira** [comment]
docker1 不需要的挂机配置 `CRZAY_JOY_COIN_ENABLE=N就行了` 
![image](https://user-images.githubusercontent.com/6993269/104917491-6f472280-59ce-11eb-9921-5cff55fe0247.png)

**Comment by hclasmn** [comment]
感谢指导谢谢
