### ISSUE TITLE
请问怎么在群晖里单独执行某个JS？

### ISSUE THREAD

**Issue by singyueyang** [LXK9301/jd_scripts#68]
按照老大的指示，才从AC转移到群晖，但平时对这方面使用较少，现在想手动执行某个JS，按日志中是调用的  node /scripts/xxxx.js  来调用的，但实际测试该命令报未找到NODE的错，请问各位大神，该如何手动执行某个JS。感谢~~~

**Comment by iouAkira** [comment]
@singyueyang 在宿主机制定docker exec -it 容器名 sh -c 'node /scripts/xxx.js'
在容器里面才可以直接执行node /scripts/xxx.js

**Comment by singyueyang** [comment]
@iouAkira   感谢大佬指点，谢谢~~
