### ISSUE TITLE
树莓派3b 无法正常运行脚本。远程仓库不能下载

### ISSUE THREAD

**Issue by gxitm** [LXK9301/jd_scripts#70]
设定远程仓库地址...

HEAD is now at c865b02 Merge pull request #49 from AboutCXJ/patch-1

git pull拉取最新代码...

fatal: unable to access 'https://gitee.com/lxk0301/jd_scripts/': error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time

**Comment by LXK9301** [comment]
多试试几次吧， 可能gitee的问题

**Comment by gxitm** [comment]
好的 ，谢谢
