### ISSUE TITLE
关于签到卡住的问题，希望来看看

### ISSUE THREAD

**Issue by a370263995** [LXK9301/jd_scripts#73]
事情是这样的 脚本昨天还可以正常运行，用Docker部署，VPS。在使用docker exec jd bash jd jd_bean_sign now进行综合签到的时候，卡在页面，只显示这些：
您的cookie选择的是用&隔开

>====================共有10个京东账号Cookie=========

> ==================脚本执行- 北京时间(UTC+8)：2021/1/19 上午7:55:06=====================
> 
> {"name":"RequestError","code":"ECONNREFUSED","timings":{"start":1611014109589,"socket":1611014109589,"lookup":1611014109616,"error":1611014109621,"phases":{"wait":0,"dns":27,"total":32}}}
> 检测到您不能访问外网,将使用CDN下载JD_DailyBonus.js文件
> 文件下载完毕
> *****************开始京东账号1 GuoSri京豆签到*******************
> 
> ⚠️⚠️⚠️⚠️目前Bark APP推送通知消息对推送内容长度有限制，如推送通知中包含此推送方式脚本会默认转换成简洁内容推送 ⚠️⚠️⚠️⚠️ 
> 
> 开始替换变量
> 替换变量完毕
> 
> 开始执行脚本签到，请稍等

然后一直卡在这个界面，不往下继续运行了，还有一些其他的脚本也是，部分脚本可以运行成功，比如炸年兽jd_nian等可以运行成功，重装过docker，vps，等等各种方法，运行docker exec jd bash jd jd_bean_sign now时都会卡在上面那个界面不会再往下进行，希望大佬们看一下，哪怕一下也行，昨天已经崩溃，希望能得到点点帮助

**Comment by LXK9301** [comment]
我自己倒是没有遇到过这个问题 😂😂😂

**Comment by Yvan0329** [comment]
早上也发现有这个问题

**Comment by LXK9301** [comment]
docker 一的话。重新从头到尾操作一波试试看吧。

或者 换lxk0301/jd_scripts镜像。然后更新看看

**Comment by fengmikaelson** [comment]
> docker 一的话。重新从头到尾操作一波试试看吧。
> 
> 或者 换lxk0301/jd_scripts镜像。然后更新看看

诶？怎么没有搜到你发布的镜像呢？

**Comment by LXK9301** [comment]
@fengmikaelson https://hub.docker.com/r/lxk0301/jd_scripts/tags?page=1&ordering=last_updated

**Comment by fengmikaelson** [comment]
> @fengmikaelson https://hub.docker.com/r/lxk0301/jd_scripts/tags?page=1&ordering=last_updated

多谢！！！不过都是docker hub上，不懂为何群晖直接搜，搜不到。

只能手动添加了。

启动web页面的话，是把enable_web_page改为true就行了吗？再自己做个端口映射。

**Comment by blucewyan** [comment]
> > @fengmikaelson https://hub.docker.com/r/lxk0301/jd_scripts/tags?page=1&ordering=last_updated
> 
> 多谢！！！不过都是docker hub上，不懂为何群晖直接搜，搜不到。
> 
> 只能手动添加了。
> 
> 启动web页面的话，是把enable_web_page改为true就行了吗？再自己做个端口映射。

这个还不太会用  和skaya一样的用法吗   也是使用一个jd_scritps.syno.json来配置吗

**Comment by fengmikaelson** [comment]
> > > @fengmikaelson https://hub.docker.com/r/lxk0301/jd_scripts/tags?page=1&ordering=last_updated
> > 
> > 
> > 多谢！！！不过都是docker hub上，不懂为何群晖直接搜，搜不到。
> > 只能手动添加了。
> > 启动web页面的话，是把enable_web_page改为true就行了吗？再自己做个端口映射。
> 
> 这个还不太会用 和skaya一样的用法吗 也是使用一个jd_scritps.syno.json来配置吗

都一样的。看docker1教程就行了

**Comment by google-mirror** [comment]
@LXK9301 
******开始【京东账号136】ioevrMQZJQsH*********

今日已签到
去做浏览商品任务任务
任务领取成功
任务完成成功，获得金币1
去做浏览商品任务任务
任务领取成功



然后后面就卡住不动了
