### ISSUE TITLE
jd_joy_reward脚本错误

### ISSUE THREAD

**Issue by iyzgit** [LXK9301/jd_scripts#81]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [X ] 没有类似的issue 

Q：是否仔细阅读了教程
- [ x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ x] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：从18号开始joy_reward就无法换京豆了，以前都能正常领取。如果去京东app的游戏中自己兑换还是可以领取的。其它脚本都正常。
js版本：宠汪汪积分兑换奖品脚本, 目前脚本只兑换京豆，兑换京豆成功，才会发出通知提示，其他情况不通知。
更新时间：2021-1-13
请看看是什么问题，谢谢
### (2) 详细日志
A：
{"name":"HTTPError","timings":{"start":1611023998998,"socket":1611023999002,"lookup":1611023999005,"connect":1611023999012,"secureConnect":1611023999036,"upload":1611023999038,"response":1611023999052,"end":1611023999054,"phases":{"wait":4,"dns":3,"tcp":7,"tls":24,"request":2,"firstByte":14,"download":2,"total":56}}}
宠汪汪积分兑换奖品 API请求失败，请检查网路重试
兑换京豆异常:undefined

### (1) Node.js版本

A：
v14.15.4
### (2) npm版本

A：6.14.10

### (3)npm install的日志

A：

**Comment by LXK9301** [comment]
检测你自己的网络设备原因吧。我自己早上还兑换了京豆

**Comment by danwangshimoluo** [comment]
我也全部是这种问题,云函数运行的。

**Comment by iyzgit** [comment]
> 检测你自己的网络设备原因吧。我自己早上还兑换了京豆

你好，我换了小火箭跑脚本的方式，在4g网上运行，也是兑换不了，难道是黑号了？？我另外一个号也是同样错误，请问有什么方法可以看到更具体的错误原因吗？

[19:21:14.630] console.log => 当前京豆库存:19137
[19:21:14.630] console.log => saleInfoId:12
[19:21:14.630] console.log => 当前账户积分:4040
当前京豆库存:19137
满足兑换条件,开始为您兑换京豆

[19:21:14.800] console.log => 兑换结果:
[19:21:14.800] console.log => {
}
[19:21:14.801] console.log => 京东服务器访问数据为空，请检查自身设备网络情况
[19:21:14.801] console.log => 兑换京豆异常:{}
[19:21:14.803] console.log => 
🔔宠汪汪积分兑换奖品, 结束! 🕛 1.241 秒
[19:21:14.803] console.log => 
[19:21:14.803] script evaluate timer release => jd_joy_reward.js

**Comment by Yvan0329** [comment]
一样的问题，之前正常。

**Comment by zyyz0110** [comment]
也遇到同样的问题

**Comment by sandyowen** [comment]
同样的问题，从18号开始，手动正常

**Comment by qqqm7** [comment]
同样的问题，从18号开始，8个号全不异常

**Comment by fengmikaelson** [comment]
> 检测你自己的网络设备原因吧。我自己早上还兑换了京豆

大佬，问一下，为什么我看default_task.log里写着，提取京东赚赚助力码；但是我看sharecode里并没有。
我去jd_jdzz.log的日志里也没找到助力码。。。应该去哪里看呢？

**Comment by LXK9301** [comment]
已修复

**Comment by LXK9301** [comment]
> > 检测你自己的网络设备原因吧。我自己早上还兑换了京豆
> 
> @LXK9301 大佬，问一下，为什么我看default_task.log里写着，提取京东赚赚助力码；但是我看sharecode里并没有。
> 我去jd_jdzz.log的日志里也没找到助力码。。。应该去哪里看呢？

京东暂时下线了互助功能
