### ISSUE TITLE
在docker中，如何执行单个js命令

### ISSUE THREAD

**Issue by MoBenw** [LXK9301/jd_scripts#82]
## 期望增加的功能

A：

## 入口

A：

**Comment by 150154906** [comment]
先ssh进入到docker内部，然后执行程序
docker exec -it jd_scripts /bin/sh
node /scripts/xxx.js

**Comment by MoBenw** [comment]
我试过一个命令可行
docker exec -it jd_scripts node jd_bean_sign.js
