### ISSUE TITLE
jd_nh脚本 兑换失败。

### ISSUE THREAD

**Issue by qingcher** [LXK9301/jd_scripts#84]
显示检查网路问题

**Comment by nosoul2018** [comment]
这个脚本好像失效了？

**Comment by xjw00654** [comment]
@qingcher @nosoul2018  求问 年货这个入口在哪里啊

**Comment by qingcher** [comment]
我也找不到入口

**Comment by LXK9301** [comment]
活动入口：
https://lzdz-isv.isvjcloud.com/dingzhi/vm/template/activity/940531?activityId=dzvm210168869301

**Comment by MisterGlasses** [comment]
这个京东年货节 好像没啥用啊
