### ISSUE TITLE
惊喜农场脚本token问题

### ISSUE THREAD

**Issue by 717785320** [LXK9301/jd_scripts#89]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否仔细阅读了教程
- [ x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] Docker1 
- [ ] Docker2 
- [ ] 系统直装 
- [x ] iOS代理软件

### (1) 具体问题
A：
惊喜农场脚本提示先获取种子token,但是token1和token2里已经有数据了,把 jd_jxnc.js第140行改成这样就好了 tokenArr.push(...[JSON.parse($.getdata('jxnc_token1')) || tokenNull, JSON.parse($.getdata('jxnc_token2')) || tokenNull]),不知是否是bug?
### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by sith1989** [comment]
good

**Comment by FanchangWang** [comment]
我看看这个，由于我没有 iOS 设备，所以并未测试 iOS 软件执行

**Comment by FanchangWang** [comment]
已提交修复 pr #155

**Comment by 717785320** [comment]
应该加个判断,为空转对象报错
tokenArr.push(...[!!$.getdata('jxnc_token1')?JSON.parse($.getdata('jxnc_token1')):tokenNull, !!$.getdata('jxnc_token2')?JSON.parse($.getdata('jxnc_token2')):tokenNull]);
