### ISSUE TITLE
云函数经常出现的错误

### ISSUE THREAD

**Issue by Arrogance-H** [LXK9301/jd_scripts#94]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] Docker1 
- [ ] Docker2 
- [ ] 系统直装 
- [ ] iOS代理软件

### (1) 具体问题
A：云函数错误

### (2) 详细日志
A：{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"SyntaxError: Unexpected token '\u003c'\n    at Request._callback (/var/user/index.js:15:22)\n    at Request.self.callback (/var/user/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:311:20)\n    at Request.\u003canonymous\u003e (/var/user/node_modules/request/request.js:1154:10)\n    at Request.emit (events.js:311:20)\n    at IncomingMessage.\u003canonymous\u003e (/var/user/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (events.js:417:28)\n    at IncomingMessage.emit (events.js:323:22)\n    at endReadableNT (_stream_readable.js:1204:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","statusCode":430}

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by LXK9301** [comment]
自己看你的index.js远程链接指向了哪个仓库。

之前被封的仓库肯定不行了

**Comment by Chen95a** [comment]
我也有这个问题，部分脚本会偶发出这些报错，index运用的是最新库的那个，选的方案二，调用的gitee库

**Comment by LXK9301** [comment]
@Chen95a gitee 有时候会不给返回数据。403

**Comment by Arrogance-H** [comment]
index.js是这个
//2.执行国内gitee远端js文件如果部署，在国内节点，选择1或2的方式
      request('https://gitee.com/lxk0301/jd_scripts/raw/master/'+v+'.js', function (error, response, body) {
       eval(response.body)
      })


START RequestId:12ddd2f5-f54d-4d54-8620-d62ba9cf6b33
2021-01-19T09:03:01.417Z 12ddd2f5-f54d-4d54-8620-d62ba9cf6b33 jd_joy_feedPets
2021-01-19T09:03:01.615Z 12ddd2f5-f54d-4d54-8620-d62ba9cf6b33 jd_joy
2021-01-19T09:03:01.617Z 12ddd2f5-f54d-4d54-8620-d62ba9cf6b33 jd_plantBean
2021-01-19T09:03:01.618Z 12ddd2f5-f54d-4d54-8620-d62ba9cf6b33 jd_dreamFactory
2021-01-19T09:03:01.618Z 12ddd2f5-f54d-4d54-8620-d62ba9cf6b33 jd_jdfactory 
ERROR RequestId:12ddd2f5-f54d-4d54-8620-d62ba9cf6b33 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"SyntaxError: Unexpected token '\u003c'\n    at Request._callback (/var/user/index.js:15:22)\n    at Request.self.callback (/var/user/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:311:20)\n    at Request.\u003canonymous\u003e (/var/user/node_modules/request/request.js:1154:10)\n    at Request.emit (events.js:311:20)\n    at IncomingMessage.\u003canonymous\u003e (/var/user/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (events.js:417:28)\n    at IncomingMessage.emit (events.js:323:22)\n    at endReadableNT (_stream_readable.js:1204:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","statusCode":430} 
END RequestId:12ddd2f5-f54d-4d54-8620-d62ba9cf6b33

把这5个放在一起跑会报错，把jd_plantBean移出去就好好的

**Comment by Arrogance-H** [comment]
更改为GitHub的库正常。
