### ISSUE TITLE
互助码获取不全

### ISSUE THREAD

**Issue by MrLinsheng** [LXK9301/jd_scripts#95]
运行jd_get_share_code后，签到领现金，炸年兽，书店获取不到，看到有人获取到了，请问一下是怎么获取到的

**Comment by LXK9301** [comment]
没及时更新

想看那个活动的就单独运行固定活动的脚本，里面日志有

**Comment by Mr-TLS** [comment]
> 没及时更新
> 
> 想看那个活动的就单独运行固定活动的脚本，里面日志有

好的，谢谢老哥
