### ISSUE TITLE
关于云函数只能运行900s的问题

### ISSUE THREAD

**Issue by Vincentzhengwei** [LXK9301/jd_scripts#96]
## 期望增加的功能

A：云函数只能是持续执行900s，然后报以下错误
{"errorCode":-1,"errorMessage":"Async invoking task timed out after 900 seconds","statusCode":433}

像joy挂机，年兽这种都没办法持续执行，或者是号比较多的情况下，也没办法好好完成任务（特别是云函数要几个js放到一个触发里面）
有没有什么优化方法？

## 入口

A：

**Comment by Clown666** [comment]
请问老哥是怎么部署得到云函数的，刚接触到这个项目，不太了解。麻烦老哥了

**Comment by dodoeye** [comment]
云函数就是这样的。自己改下触发器拆开运行，或者复制函数每个函数运行一个账号就好了，挂机的你就每隔一段时间运行一次不就连起来了嘛

**Comment by Vincentzhengwei** [comment]
> 云函数就是这样的。自己改下触发器拆开运行，或者复制函数每个函数运行一个账号就好了，挂机的你就每隔一段时间运行一次不就连起来了嘛

恐怕只能这样了

**Comment by LXK9301** [comment]
@Vincentzhengwei readme上面。我已经把云函数的脚本入口给去掉了

**Comment by Vincentzhengwei** [comment]
> @Vincentzhengwei readme上面。我已经把云函数的教程入口给去掉了

找了一下，readme上好像没有关于优化运行900s的方法
