### ISSUE TITLE
Surge 运行年兽脚本，日志显示 Untitled 超时

### ISSUE THREAD

**Issue by byteat** [LXK9301/jd_scripts#98]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] Docker1 
- [ ] Docker2 
- [ ] 系统直装 
- [x] iOS代理软件

### (1) 具体问题
A：Surge 运行年兽脚本，一会就自动中断，查看日志，发现某个环节超时，但我设置的超时是200s

### (2) 详细日志
A：🔔京东炸年兽🧨, 开始!
21:13:29.664914 开始获取京东炸年兽🧨配置文件

21:13:29.664976 共1个京东账号

21:13:29.665052 您提供了0个账号的京东炸年兽🧨助力码

21:13:29.973226 
****开始【京东账号1】*******

21:13:29.974286 由于您第1个京东账号未提供shareCode,将采纳本脚本自带的助力码

21:13:29.974687 开始
21:13:32.157900 第1个京东账号将要助力的好友["cgxZaDXWZPCmiUa2akPVmFMI27K6antJzucULQPYNim_BPEW1Dwd","cgxZdTXtIrPYuAqfDgSpusxr97nagU6hwFa3TXxnqM95u3ib-xt4nWqZdz8","cgxZdTXtIO-O6QmYDVf67KCEJ19JcybuMB2_hYu8NSNQg0oS2Z_FpMce45g","cgxZdTXtILiLvg7OAASp61meehou4OeZvqbjghsZlc3rI5SBk7b3InUqSQ0","cgxZ9_MZ8gByP7FZ368dN8oTZBwGieaH5HvtnvXuK1Epn_KK8yol8OYGw7h3M2j_PxSZvYA"]
21:13:32.307332 当前爆竹58694🧨，下一关需要422000🧨
21:13:32.307424 可收取的爆竹大于0，去收取爆竹
21:13:32.378228 收取成功，获得54爆竹🧨
21:13:37.861752 随机取5个码放到您固定的互助码后面(不影响已有固定互助)
21:13:39.003431 当前已开启的地图：小镇车站 
2021-01-19 21:13:39.680455 <WARNING> [SGJSVM] Script Untitled timeout

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by LXK9301** [comment]
。。。。。。

首先。你这是软件使用问题。你不会

麻烦把timeout 改大一些

222000如何？

**Comment by byteat** [comment]
> 。。。。。。
> 
> 首先。你这是软件使用问题。你不会
> 
> 麻烦把timeout 改大一些
> 
> 222000如何？

改大了一样，还是只能运行10s左右。
